### ISSUE TITLE
Net Command Output

### ISSUE THREAD

**Issue by seahop** [HavocFramework/Havoc#101]
When running net logons, sessions, users, etc, I am getting some strange output, and the occasional character missing

![netoutput](https://user-images.githubusercontent.com/88900815/193380747-d76b92b8-4908-4d2c-b1b3-567f44aa222b.jpg)

**Comment by seahop** [comment]
Slightly more context, running TS/Client on Kali, implant on Win11 x64

**Comment by iNoSec2** [comment]
Same problem in arch linux for TS/Client and implant on win10 x64

**Comment by iNoSec2** [comment]
Still has the same problem
