### ISSUE TITLE
Demon agent fails to callback to HTTPS listener if '/' inside URI.

### ISSUE THREAD

**Issue by iilegacyyii** [HavocFramework/Havoc#103]
After some testing it appears that the following URI's fail to call back at all. They decrypt correctly in memory, and have confirmed this via process hacker.

- `js/jquery-3.4.4.js`
- `/js/jquery-3.4.4.js`
- `api/login.php`
- `/api/login.php`

Changing these to something like `test.html` works no problem.

**Comment by Cracked5pider** [comment]
this issue has been fixed in commit: 8dda1dd
