### ISSUE TITLE
Module not imported

### ISSUE THREAD

**Issue by iNoSec2** [HavocFramework/Havoc#106]
When i import module, powerpick for example, it is listed in the help command but when trying to use it 
![image](https://user-images.githubusercontent.com/51358868/193409065-ce20d285-d06e-4703-89e8-dfc040d8fbe0.png)

![image](https://user-images.githubusercontent.com/51358868/193409038-72b4f42b-7f92-499d-a14e-1b1a3a910b91.png)

![image](https://user-images.githubusercontent.com/51358868/193408997-6bc39008-d17a-417e-b2b5-404193ea8aae.png)

im on arch for TS and client, the implant is running on win10

**Comment by Cracked5pider** [comment]
fixed in commit: [19e6f88](https://github.com/HavocFramework/Havoc/commit/19e6f88e3cf51b0a1543647d8c9ae479e1d7f424)
