### ISSUE TITLE
process list and file explorer can only be opened once

### ISSUE THREAD

**Issue by rhakb** [HavocFramework/Havoc#107]
When close it ,Can't open it again

**Comment by lantubu** [comment]
one session can only be opened once

**Comment by iNoSec2** [comment]
you must at least give the OS version you run the TS/Client and the target implant...

**Comment by lantubu** [comment]
ts/client debian11
implant windows server2019

**Comment by lantubu** [comment]
have another little problem，implant is on windows server2019，but checkin show this is windows10

**Comment by iNoSec2** [comment]
I have the same problem, it Can be open only once.
Im on arch for ts/client and implant on win10

**Comment by iNoSec2** [comment]
Commit resolution please?

**Comment by rhakb** [comment]
> Commit resolution please?

now it's ok，Just open process list is break
