### ISSUE TITLE
Graph default positions are weird

### ISSUE THREAD

**Issue by CodeXTF2** [HavocFramework/Havoc#11]
![image](https://user-images.githubusercontent.com/29991665/189588715-9b1fc231-4118-41f3-93f4-1c34401e7859.png)
also the max zoom out is not enough, especially with longer beacon chains. Maybe increase the maximum zoom out.

**Comment by iNoSec2** [comment]
I agree for an increase zoom out because if we have an AD pentest we will have a little problem

**Comment by CodeXTF2** [comment]
![image](https://user-images.githubusercontent.com/29991665/196780620-4fbedb6c-13c6-4235-9dea-816cbd1e0958.png)

**Comment by iNoSec2** [comment]
> ![image](https://user-images.githubusercontent.com/29991665/196780620-4fbedb6c-13c6-4235-9dea-816cbd1e0958.png)

XD
