### ISSUE TITLE
Host Name?

### ISSUE THREAD

**Issue by vysecurity** [HavocFramework/Havoc#111]
I'm a bit lost, perhaps didn't read the guide properly but where is the box for the "host name"?

Edit: turns out you have to set /etc/hosts to your IP and prospective domain name.

Edit2: after generating an implant, it doesn't call out. It tries to connect to the right IP, but no shell comes back. Tried intercepting with a proxy in system settings and it doesn't seem to adopt HTTP proxy settings.

**Comment by SleekZ** [comment]
You should be your local IP (the one running Havoc) into the host name.

**Comment by chvancooten** [comment]
This is a duplicate of https://github.com/HavocFramework/Havoc/issues/93. I've also outlined a workaround there.

**Comment by Cracked5pider** [comment]
added support for multiple callback hosts (can be domains, IP addresses etc.). in commit: [ee8ea90](https://github.com/HavocFramework/Havoc/commit/ee8ea90b1522d88c13623ffcfce381bf7513769b)
Let me know if it's working for you guys and report any issues/bugs. Thanks.

**Comment by chvancooten** [comment]
That looks awesome, thanks for the quick and thorough fix! I will test if it behaves as expected as soon as I'm able. Thanks again for your great work 🙏

**Comment by Cracked5pider** [comment]
Glad to hear that !!!!
