### ISSUE TITLE
file or dir character display error

### ISSUE THREAD

**Issue by lantubu** [HavocFramework/Havoc#112]
if file or dir is not English，A character error will occur, file explorer have too, and connot open dir 

![one](https://user-images.githubusercontent.com/22503688/193434189-8d613d2e-d471-47e9-ad2e-afc1b232afe7.png)

**Comment by Cracked5pider** [comment]
Alright, gotcha. What system do you have?

**Comment by lantubu** [comment]
> Alright, gotcha. What system do you have?

It seems that all systems have this problem，i use windows server2019 and 2012(English system),It seems that other software is solved by unicode function, But cs seems to have other solutions, i don't know
