### ISSUE TITLE
"proc find-module" doesnt work

### ISSUE THREAD

**Issue by iNoSec2** [HavocFramework/Havoc#114]
The `proc find-module` command doesnt, it is like it isnt registered. I cant look at the code during 1 week so i can only report stuff and cant PR.
![image](https://user-images.githubusercontent.com/51358868/193442650-4d497ea4-d9aa-4a6e-97e1-f86b784dcd66.png)

implant:
![image](https://user-images.githubusercontent.com/51358868/193442690-32b13c0d-5c9a-417c-bb64-6f93ffa0b1c2.png)

**Comment by Cracked5pider** [comment]
It is a placeholder. going to remove it in the next commit since I didn't plan to include it in the agent.

**Comment by iNoSec2** [comment]
Ok but it isnt in the GUI of proc listing, it is the cli. Dont remove it i will make a PR in the next 2 week because that's really interesting to have when we inject/Spawn assembly to know which process already have clr it is more opsec/blend in than spwmawning clr in notepad for example :) or maybe i can make a module for dotnet command to complete the already existent stuff, there is already a good template with invoke assembly module

**Comment by Cracked5pider** [comment]
Well I don't wanna have that in my bins for size reasons and there is already a BOF which I can port to Havoc: https://github.com/outflanknl/FindObjects-BOF (I might make a PR to that repo or fork it)

**Comment by Cracked5pider** [comment]
removed in commit: [19bd113](https://github.com/HavocFramework/Havoc/commit/19bd113a9b3fa465ce5d7227b1930695d1795519)
