### ISSUE TITLE
Module InvokeAssembly doesnt work

### ISSUE THREAD

**Issue by iNoSec2** [HavocFramework/Havoc#116]
The module InvokeAssembly has some weird problems, it seems the module is loaded because if i delete it and load it again in the script manager, i have this output in my terminal console
![image](https://user-images.githubusercontent.com/51358868/193443943-0a659691-8db4-4726-8379-28ae4fa54b68.png)
but it doesnt appear in the help command nor it doesnt executes it.
![image](https://user-images.githubusercontent.com/51358868/193444000-b656ac6a-88ba-4f49-9c7e-aa8b14b692be.png)

**Comment by Cracked5pider** [comment]
the InvokeAssembly is registered under `dotnet` module. try to type `help dotnet`

**Comment by iNoSec2** [comment]
Hmmm ok i will look at it more closely ^^ 
Since we are here what is the 2nd argument for registercommand function?
Will go through the code if needed

**Comment by Cracked5pider** [comment]
The second argument for RegisterCommand is the module string where to register the command.

**Comment by iNoSec2** [comment]
Ok it is logic now that i know it lmao
That's awesome how you made all modular!!! Thanks for your hard work
