### ISSUE TITLE
CMake Error at CMakeLists.txt:166 

### ISSUE THREAD

**Issue by nocomp** [HavocFramework/Havoc#120]
hi,
very pleased to fnd this project, get an issue on ubuntu when compiling:

-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.8.so (found version "3.8.10")
CMake Error at CMakeLists.txt:166 (find_package):
  By not providing "Findspdlog.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "spdlog", but
  CMake did not find one.

  Could not find a package configuration file provided by "spdlog" with any
  of the following names:

    spdlogConfig.cmake
    spdlog-config.cmake

  Add the installation prefix of "spdlog" to CMAKE_PREFIX_PATH or set
  "spdlog_DIR" to a directory containing one of the above files.  If "spdlog"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!

Best regards

**Comment by Nixiabing** [comment]
me too

**Comment by Cracked5pider** [comment]
you need to install spdlog library

**Comment by Cracked5pider** [comment]
Please in the future read the WIKI.md or the README.md in the Client folder. Thanks

**Comment by Tardis07** [comment]
`libspdlog-dev` installed, but the error still exist. Does anyone find the solution?
