### ISSUE TITLE
macOS support?

### ISSUE THREAD

**Issue by meichengg** [HavocFramework/Havoc#121]
Hi, is it possible that macOS (m1/intel) can be supported?

**Comment by Cracked5pider** [comment]
Yes it is possible since QT is a cross-compile library, and the teamserver can also be compiled for arm CPUs. But I need someone to add support for me since I got no access to a macOS laptop with m1 or intel CPU.

**Comment by meichengg** [comment]
I can help with that, lemme know what you need.

**Comment by Cracked5pider** [comment]
you can try compiling the teamserver and or the client and let me know what kind of errors you get etc.

**Comment by meichengg** [comment]
I got this when building `teamserver`.

![image](https://user-images.githubusercontent.com/25204246/193570505-37d0934b-ae37-4421-ba0b-b08201514d2d.png)

**Comment by meichengg** [comment]
And this is what i got when building `client`.

[logs-building-client.log](https://github.com/HavocFramework/Havoc/files/9697247/logs-building-client.log)

**Comment by meichengg** [comment]
With a bit custom in `Build.sh` file to make the building process work on macOS.

```
mkdir Build
cd Build
cmake .. -DQt5_DIR=$(brew --prefix qt5)/lib/cmake/Qt5
cd ..
cmake --build Build -- -j 4 
```

**Comment by Cracked5pider** [comment]
If you manage to make working client and or teamserver arm build for macOS then just make a pull request.

**Comment by AnubisSec** [comment]
For M1 Mac I got the Client to work with:
-  `brew install qt5`
- `brew install spdlog`
 
- `cmake .. -DQt5_DIR=$(brew --prefix qt5)/lib/cmake/Qt5 -DPYTHON_LIBRARY=$(python3-config --prefix)/lib/libpython3.9.dylib -DPYTHON_INCLUDE_DIR=$(python3-config --prefix)/include/python3.9`

Then changing all instances of `Python.h` and `structmember.h` to the following (respectively): 
- `/opt/homebrew/Cellar/python@3.10/3.10.5/Frameworks/Python.framework/Headers/Python.h` 
- `/opt/homebrew/Cellar/python@3.10/3.10.5/Frameworks/Python.framework/Headers/structmember.h`

**Comment by rundro** [comment]
The client appears to compile minus one error for me using @AnubisSec edits. it fails at about 99% with the following error. I've installed xcode command line tools and theyre up to date. I confirmed ld is installed on the system. I installed full xcode as well. Any ideas?
```
1 warning generated.
gmake[1]: *** [CMakeFiles/Makefile2:84: CMakeFiles/Havoc.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2

ld: library not found for -lSystem

ld: library not found for -lc++
```

**Comment by AnubisSec** [comment]
@rundro do you have gcc installed? 
`brew install gcc`

**Comment by rundro** [comment]
> ld: library not found for -lSystem

I do, I've tried reinstalling as well with no luck.

**Comment by Cracked5pider** [comment]
Thanks a lot @AnubisSec for testing it out. Feel free to make a pull request.

**Comment by AnubisSec** [comment]
> 

No problem man! Love the framework so far, if i get some more spare time i'll make a PR for ya

**Comment by AnubisSec** [comment]
> > ld: library not found for -lSystem
> 
> I do, I've tried reinstalling as well with no luck.

Im also seeing that possibly `xcode-select --install` might help fix it, tho i know you mentioned youve already verified your xcode. Might be worth a shot, but sorry I don't know too much on what that could be.

**Comment by sudonoodle** [comment]
I am getting similar behaviour as @rundro. 

Been working at this for a good few hours, not sure what to try next...

```text
<--SNIP-->

[ 92%] Building CXX object CMakeFiles/Havoc.dir/Source/Util/Base64.cpp.o
[ 94%] Building CXX object CMakeFiles/Havoc.dir/Source/Util/StructPack/struct.cpp.o
[ 96%] Building CXX object CMakeFiles/Havoc.dir/Source/Util/Base.cpp.o
gmake[2]: *** No rule to make target '/Library/Frameworks/Python.framework/Versions/3.8/lib/libpython3.9.dylib', needed by '/Users/user/Developer/Havoc/Client/Havoc'.  Stop.
gmake[2]: *** Waiting for unfinished jobs....
[ 98%] Building CXX object CMakeFiles/Havoc.dir/Havoc_autogen/EWIEGA46WW/qrc_Havoc.cpp.o
gmake[1]: *** [CMakeFiles/Makefile2:84: CMakeFiles/Havoc.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2
```

**Comment by fhlip0** [comment]
this works for me on an M1 mac

brew install python gcc spdlog cmake qt5
git clone https://github.com/HavocFramework/Havoc
cd Havoc/Client
mkdir Build
cd Build
cmake .. -DQt5_DIR=$(brew --prefix qt5)/lib/cmake/Qt5 -DPYTHON_LIBRARY=/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/libpython3.10.dylib -DPYTHON_INCLUDE_DIR=/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Headers/
cd ..
cp -r /opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Headers/* ./
cmake --build Build

**Comment by m57** [comment]
> this works for me on an M1 mac
> 
> brew install python gcc spdlog cmake qt5 git clone https://github.com/HavocFramework/Havoc cd Havoc/Client mkdir Build cd Build cmake .. -DQt5_DIR=$(brew --prefix qt5)/lib/cmake/Qt5 -DPYTHON_LIBRARY=/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/libpython3.10.dylib -DPYTHON_INCLUDE_DIR=/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Headers/ cd .. cp -r /opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Headers/* ./ cmake --build Build

Can confirm this works for me too. Thanks fhlip0

**Comment by rundro** [comment]
@fhlip0 solution works, thanks!

**Comment by sudonoodle** [comment]
This worked for me:

```text
brew install python gcc spdlog cmake qt5

git clone https://github.com/HavocFramework/Havoc.git
cd Havoc/Client/
mkdir Build
cd Build
cp -r /usr/local/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Headers/* ./
cmake .. -DQt5_DIR=$(brew --prefix qt5)/lib/cmake/Qt5 -DPYTHON_LIBRARY=/Library/Frameworks/Python.framework/Versions/3.8/lib/libpython3.8.dylib -DPYTHON_INCLUDE_DIR=/Library/Frameworks/Python.framework/Versions/3.8/include/python3.8
cd ..
cmake --build Build
./Havoc
```

Aside from font and UI issues, seems to work just fine.

![havoc](https://user-images.githubusercontent.com/52385049/193918698-36883f31-e5ce-4b20-8293-69c68400d6dc.png)

**Comment by meichengg** [comment]
> This worked for me:
> 
> ```
> brew install python gcc spdlog cmake qt5
> 
> git clone https://github.com/HavocFramework/Havoc.git
> cd Havoc/Client/
> mkdir Build
> cd Build
> cp -r /usr/local/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Headers/* ./
> cmake .. -DQt5_DIR=$(brew --prefix qt5)/lib/cmake/Qt5 -DPYTHON_LIBRARY=/Library/Frameworks/Python.framework/Versions/3.8/lib/libpython3.8.dylib -DPYTHON_INCLUDE_DIR=/Library/Frameworks/Python.framework/Versions/3.8/include/python3.8
> cd ..
> cmake --build Build
> ./Havoc
> ```
> 
> Aside from font and UI issues, seems to work just fine.
> 
> ![havoc](https://user-images.githubusercontent.com/52385049/193918698-36883f31-e5ce-4b20-8293-69c68400d6dc.png)

I followed your guide but i got these errors and don't know how to fix.

```
$ cmake --build Build
[  1%] Automatic MOC and UIC for target Havoc
[  1%] Built target Havoc_autogen
[  3%] Automatic RCC for Havoc.qrc
[  5%] Building CXX object CMakeFiles/Havoc.dir/Havoc_autogen/mocs_compilation.cpp.o
In file included from /Users/user/Downloads/Havoc/Client/Build/Havoc_autogen/mocs_compilation.cpp:2:
In file included from /Users/user/Downloads/Havoc/Client/Build/Havoc_autogen/BEIJ4H4JXG/moc_SessionGraph.cpp:10:
In file included from /Users/user/Downloads/Havoc/Client/Build/Havoc_autogen/BEIJ4H4JXG/../../../Include/UserInterface/Widgets/SessionGraph.hpp:4:
In file included from /Users/user/Downloads/Havoc/Client/Include/global.hpp:13:
In file included from /usr/local/opt/qt@5/lib/QtWidgets.framework/Headers/QMenu:1:
/usr/local/opt/qt@5/lib/QtWidgets.framework/Headers/qmenu.h:238:31: error: non-virtual member function marked 'override' hides virtual member function
    void enterEvent(QEvent *) override;
                              ^
/usr/local/include/QtWidgets/qwidget.h:703:18: note: hidden overloaded virtual function 'QWidget::enterEvent' declared here: type mismatch at 1st parameter ('QEnterEvent *' vs 'QEvent *')
    virtual void enterEvent(QEnterEvent *event);
                 ^
In file included from /Users/user/Downloads/Havoc/Client/Build/Havoc_autogen/mocs_compilation.cpp:2:
In file included from /Users/user/Downloads/Havoc/Client/Build/Havoc_autogen/BEIJ4H4JXG/moc_SessionGraph.cpp:10:
In file included from /Users/user/Downloads/Havoc/Client/Build/Havoc_autogen/BEIJ4H4JXG/../../../Include/UserInterface/Widgets/SessionGraph.hpp:4:
In file included from /Users/user/Downloads/Havoc/Client/Include/global.hpp:13:
In file included from /usr/local/opt/qt@5/lib/QtWidgets.framework/Headers/QMenu:1:
/usr/local/opt/qt@5/lib/QtWidgets.framework/Headers/qmenu.h:275:8: error: an attribute list cannot appear here
inline QT_DEPRECATED void qt_mac_set_dock_menu(QMenu *menu) { menu->setAsDockMenu(); }
       ^~~~~~~~~~~~~
/usr/local/include/QtCore/qglobal.h:351:25: note: expanded from macro 'QT_DEPRECATED'
#  define QT_DEPRECATED Q_DECL_DEPRECATED
                        ^~~~~~~~~~~~~~~~~
/usr/local/include/QtCore/qcompilerdetection.h:1119:29: note: expanded from macro 'Q_DECL_DEPRECATED'
#  define Q_DECL_DEPRECATED [[deprecated]]
                            ^~~~~~~~~~~~~~
In file included from /Users/user/Downloads/Havoc/Client/Build/Havoc_autogen/mocs_compilation.cpp:2:
In file included from /Users/user/Downloads/Havoc/Client/Build/Havoc_autogen/BEIJ4H4JXG/moc_SessionGraph.cpp:10:
In file included from /Users/user/Downloads/Havoc/Client/Build/Havoc_autogen/BEIJ4H4JXG/../../../Include/UserInterface/Widgets/SessionGraph.hpp:4:
In file included from /Users/user/Downloads/Havoc/Client/Include/global.hpp:23:
In file included from /usr/local/opt/qt@5/lib/QtCore.framework/Headers/QJsonDocument:1:
/usr/local/opt/qt@5/lib/QtCore.framework/Headers/qjsondocument.h:114:5: error: division by zero in preprocessor expression
#if QT_CONFIG(binaryjson) && QT_DEPRECATED_SINCE(5, 15)
    ^~~~~~~~~~~~~~~~~~~~~
/usr/local/include/QtCore/qglobal.h:107:30: note: expanded from macro 'QT_CONFIG'
#define QT_CONFIG(feature) (1/QT_FEATURE_##feature == 1)
                            ~^~~~~~~~~~~~~~~~~~~~~
In file included from /Users/user/Downloads/Havoc/Client/Build/Havoc_autogen/mocs_compilation.cpp:2
```

**Comment by meichengg** [comment]
@Cracked5pider the font after building on mac in quite small though, i mean very small

**Comment by Cracked5pider** [comment]
I can't do much since i don't have a mac...
You can change the font in the Client source main under Source/Main.cpp

**Comment by hdbreaker** [comment]
It would be great a docker image that just start the whole thing...
