### ISSUE TITLE
Setting different listener bind port than C2 address?

### ISSUE THREAD

**Issue by rundro** [HavocFramework/Havoc#122]
I didn't see any way to set a different local bind port than the c2 traffic. For instance, cobaltstrike lets you send c2 traffic to 443 while binding to 8443. Is there a way to do this with Havoc?

![image](https://user-images.githubusercontent.com/52337715/193643922-b6fb469d-b800-469e-88d0-8e4efdfe9a8d.png)

**Comment by iNoSec2** [comment]
You Can use portforwarding at the OS level if you really need it

**Comment by rundro** [comment]
Update: I was able to configure this by using the docker teamserver image with port forwards.
