### ISSUE TITLE
error: incomplete type ‘QDate’ used in nested name specified

### ISSUE THREAD

**Issue by tejas15802** [HavocFramework/Havoc#135]
I had installed everything as mentioned in the Wiki for Ubuntu. I got error `error: incomplete type ‘QDate’ used in nested name specified` when I ran `Install.sh`. 
OS: Ubuntu
Version: 20.04.5 LTS

![image](https://user-images.githubusercontent.com/47889755/194045490-0cf1956a-beba-490b-b358-88c0b382687b.png)

Though at the end it says it's built, but the file isn't built properly (It doesn't run).

**Comment by m57** [comment]
You need to run Ubuntu 22.04 or setup backported QT libraries. This has already been discussed

**Comment by tejas15802** [comment]
I'm sorry, didn't notice it. 

> You need to run Ubuntu 22.04 or setup backported QT libraries. This has already been discussed
