### ISSUE TITLE
Error handling in teamserver

### ISSUE THREAD

**Issue by trickster0** [HavocFramework/Havoc#137]
![image](https://user-images.githubusercontent.com/20028117/194111616-4a2ea5de-7744-4128-ae8d-8c75bc3e840c.png)

No error handling running
./teamserver server XXXXXXXXXX

**Comment by trickster0** [comment]
sudo ./teamserver -d 
just exits the teamserver without starting with a default profile.

**Comment by trickster0** [comment]
Weird yea I was using the server just forgot to write it. It wasn't working for me weird

**Comment by Cracked5pider** [comment]
fixed it in commit: [31db84b](https://github.com/HavocFramework/Havoc/commit/31db84b432d57d7f5d234791455b18260f00cd40)
