### ISSUE TITLE
Listener not detected by payload window

### ISSUE THREAD

**Issue by trickster0** [HavocFramework/Havoc#138]
Listener is not detected by the payload generator(payload window) if it was created directly from profile.yaotl.

Creating a listener from listener works though.

![image](https://user-images.githubusercontent.com/20028117/194113083-ebfbf2e8-aac9-43fc-9e44-076d09f450a4.png)

**Comment by iNoSec2** [comment]
It worked before when i tested it so it must a changed in the last few days, just write that to help in tracking the issue

**Comment by Cracked5pider** [comment]
Can you share the profile used?

**Comment by S4ntiagoP** [comment]
this is working on `dev`, reopen if needed
