### ISSUE TITLE
File Explorer [Client]

### ISSUE THREAD

**Issue by dmcxblue** [HavocFramework/Havoc#141]
When utilizing File Explorer the Path Box does not contain the ":" when starting to explore on the C:\ Path, when moving onto another folder it removes any parent paths. For example:
If I am on C:\Users then access C:\Users\HelpDesk the path "Users" gets removed and only C\HelpDesk gets woorked on.
Pardon my poor explanation but here is a GIF
![Havoc-FE](https://user-images.githubusercontent.com/41899653/194177168-ca18c108-36ff-4afd-8cf6-ed68c19296dc.gif)

OS: Linux blackarch 5.19.11-arch1-1
Havoc: 0.10
Repo Pulled on: Wednesday October 5 2022 3pm PST

**Comment by Cracked5pider** [comment]
should be fixed in [d98f8b6](https://github.com/HavocFramework/Havoc/commit/d98f8b692b9c0fe79b6d153b6f34167589082789)
