### ISSUE TITLE
pivot connect error

### ISSUE THREAD

**Issue by useragent23253** [HavocFramework/Havoc#144]
I got error while try to pivot 2 virtual machines. Any suggestions? or it's still unavailable?
[!] [SMB] Failed to connect: ERROR_INVALID_HANDLE [6]

**Comment by Cracked5pider** [comment]
It couldn't connect to the pivot. 
This means that either the agent isn't running or you mistyped the pivot pipe name. Do you mind sharing the command line you passed in the console?

**Comment by useragent23253** [comment]
07/10/2022 09:34:10 [admin] Demon » pivot connect DESKTOP-TC 4883F4A
[*] [F63529BD] Tasked demon to connect to a smb pivot: \\DESKTOP-TC\pipe\4883F4A
[+] Send Task to Agent [76 bytes]
[!] [SMB] Failed to connect: ERROR_INVALID_HANDLE [6]

everting is correct
pivot connect myhostname agentname

**Comment by Cracked5pider** [comment]
Alright after some testing out it seems that it works well. You can only connect to a remote pipe if you have access to it. Keep that in mind. 
![image](https://user-images.githubusercontent.com/51360176/194761319-d732e86b-c1d3-4ff0-b629-8a4a346d0b04.png)

**Comment by useragent23253** [comment]
Forgot to say that I was trying to pivot 2 different subnets..
do u plan to add something like proxy ?

**Comment by Cracked5pider** [comment]
yeah, I am going to add a socks4a proxy soon.
