### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by InfosecWestwood6969** [HavocFramework/Havoc#148]
### Contact Details

infosecwestwood6969@gmail.com

### What is the idea?

Starting multiple listener crashes the team server randomly. Sometimes it works, sometimes it doesn't. Please fix it already.

### Is_it_already_in?

Yes (You didn't check...)

### Are-You-Trolling?

- [X] I declare I made an effort and provided the necessary information for an understanding of the feature by the Framework authors.

**Comment by InfosecWestwood6969** [comment]
why closed without fix?

**Comment by Cracked5pider** [comment]
![image](https://user-images.githubusercontent.com/51360176/194718114-ff501157-ea5a-4f18-abcc-b214884d01d4.png)

**Comment by Cracked5pider** [comment]
Why I closed this issue? This feels like a troll issue and I don't have time for that. If this is a real issue provide more info than just "listener crashes the team server randomly. Sometimes it works, sometimes it doesn't". Thank you for your time.
