### ISSUE TITLE
Couldn't compile implant:

### ISSUE THREAD

**Issue by kmwolf9** [HavocFramework/Havoc#155]
### What is the idea?

![image](https://user-images.githubusercontent.com/105093035/194862310-2b4adfef-dd18-412b-8a6d-862fb3b1854f.png)

### Is_it_already_in?

No (You checked and it doesn't.)

### Are-You-Trolling?

- [X] I declare I made an effort and provided the necessary information for an understanding of the feature by the Framework authors.

**Comment by Cracked5pider** [comment]
Try to use the ``Install.sh`` script. It is going to install the needed compiler.
