### ISSUE TITLE
File Explorer Drive formatting issue

### ISSUE THREAD

**Issue by rafale0n** [HavocFramework/Havoc#156]
First of all thanks dude for such an awesome project. I like how you got the inspiration from Cobalt, learning curve definitely goes down. 

Now off to the issue, just pulled and built latest release. File Explorer is missing drive characters " :\ " to browse the folders. It works if you specify the path manually but clicking on the folders does not open the path. Here is the screenshot:

![image](https://user-images.githubusercontent.com/77019753/194962217-c9e31961-2fce-4cf4-ab7e-5c6921428df5.png)

![image](https://user-images.githubusercontent.com/77019753/194962143-1de67fd7-aa1a-4c91-8b56-fb9fa4d469c3.png)

Many thanks!

**Comment by Cracked5pider** [comment]
Thanks for the report. I am already aware of this issue and i am going to fix this soon. This is because i changed the fs commands from ascii to wide strings and i need to update the File Explorer too. Many thanks for checking it out and reporting issues to me.

**Comment by rafale0n** [comment]
Cheers for a quick response

**Comment by Cracked5pider** [comment]
should be fixed in [d98f8b6](https://github.com/HavocFramework/Havoc/commit/d98f8b692b9c0fe79b6d153b6f34167589082789)
