### ISSUE TITLE
[Feature Suggestions/Enhancements]: Allow profiles to be deleted from the panel

### ISSUE THREAD

**Issue by rafale0n** [HavocFramework/Havoc#157]
### What is the idea?

It would be very useful to have an option to delete profiles from the panel:

![image](https://user-images.githubusercontent.com/77019753/195199251-6ac64de4-1698-48ca-9290-4d47f2b1bb71.png)

Many thanks!

### Is_it_already_in?

No (You checked and it doesn't.)

### Are-You-Trolling?

- [X] I declare I made an effort and provided the necessary information for an understanding of the feature by the Framework authors.

**Comment by Cracked5pider** [comment]
You can delete profiles from the panel. 
![Peek 2022-10-12 03-18](https://user-images.githubusercontent.com/51360176/195226924-357dea7f-ce3b-4371-a500-c2751e4964f1.gif)
