### ISSUE TITLE
pivot - how to use ?

### ISSUE THREAD

**Issue by protrading104** [HavocFramework/Havoc#158]
Is there something wrong on my side ?

Operating System:
  - Version            : Windows 10
  - Build              : 10.0.1.0.19043
  - Arch               : x64/AMD64

![image](https://user-images.githubusercontent.com/71656833/195212437-055c30b0-a52d-47c2-85f6-4d975524194d.png)

**Comment by Cracked5pider** [comment]
`ERROR_INVALID_HANDLE` means that it couldn't open the specified pipe name. Keep in mind that you need to have access to that remote host. the demon agent uses CreateFileW to connect to the specified pipe named. So you need to have READ/WRITE access to that pipe.
