### ISSUE TITLE
No output with dotnet inline-execute on an SMB pivot

### ISSUE THREAD

**Issue by umbra-romae** [HavocFramework/Havoc#168]
### What happened?

Can't retrieve the output of when using dotnet execute / inline-execute with an SMB pivot.

### Did You Do a Pull First?

Latest (You performed a pull first)

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by mohinparamasivam** [comment]
![image](https://user-images.githubusercontent.com/28557040/196089759-59b5883b-a5a7-4693-b04b-4488ad6a27b3.png)
https://github.com/HavocFramework/Havoc/blob/main/WIKI.MD#agents

**Comment by dmcxblue** [comment]
Same
![image](https://user-images.githubusercontent.com/41899653/200745497-88a74963-c36b-4686-850d-ed046d6af9ec.png)

**Comment by S4ntiagoP** [comment]
This is working on the `dev` branch, reopen if needed.
