### ISSUE TITLE
Fatal error during build process - killed signal

### ISSUE THREAD

**Issue by jcxhunter123** [HavocFramework/Havoc#172]
### Contact Details

jcxhunter123@gmail.com

### What happened?

Trying building the client on the cloud but got the following fatal error during compilation with a fatal error. I have installed all the dependencies as required.

![Havoc_fatalerror](https://user-images.githubusercontent.com/24419860/196039811-6cd20029-11d6-4851-bd3e-89c5924251c1.png)

### Did You Do a Pull First?

Latest (You performed a pull first)

### Relevant log output

```shell
mkdir: cannot create directory ‘Build’: File exists
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/Havoc/Client/Build
Scanning dependencies of target Havoc_autogen
[  1%] Automatic MOC and UIC for target Havoc
[  1%] Built target Havoc_autogen
[  3%] Automatic RCC for Data/Havoc.qrc
Scanning dependencies of target Havoc
[  5%] Building CXX object CMakeFiles/Havoc.dir/Source/Havoc/Connector.cpp.o
[  7%] Building CXX object CMakeFiles/Havoc.dir/Source/Main.cpp.o
[  9%] Building CXX object CMakeFiles/Havoc.dir/Havoc_autogen/mocs_compilation.cpp.o
[ 11%] Building CXX object CMakeFiles/Havoc.dir/Source/Havoc/Packager.cpp.o



c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[3]: *** [CMakeFiles/Havoc.dir/build.make:146: CMakeFiles/Havoc.dir/Source/Havoc/Connector.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
```

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by Cracked5pider** [comment]
This is not an issue with the Client or building process. Your system is killing it because of a lack of CPU/memory.

**Comment by Cracked5pider** [comment]
Try to change this line and remove the ``-j 4`` https://github.com/HavocFramework/Havoc/blob/main/Client/makefile#L9
