### ISSUE TITLE
i have a Qt5 issue when i try to install it can you help me to fix this issue

### ISSUE THREAD

**Issue by shadhack** [HavocFramework/Havoc#173]

**Comment by Cracked5pider** [comment]
LMAO

**Comment by mohinparamasivam** [comment]
sudo apt-get install qtbase5-dev
sudo apt-get install qtdeclarative5-dev

**Comment by Cracked5pider** [comment]
@shadhack can you please provide more info than that ? or else I am going to close the issue.
