### ISSUE TITLE
[Teamserver-Client--Bug]: execuiton of situational aweressness bof modules

### ISSUE THREAD

**Issue by zufukatana** [HavocFramework/Havoc#178]
### What happened?

cant execute bof files of situationalawaressness module

### Did You Do a Pull First?

Latest (You performed a pull first)

### Relevant log output

```shell
Traceback (most recent call last):
  File "<string>", line 11, in dcenum
TypeError: argument 4 must be str, not bytes

For all commands of sistuational awareness
```

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by Cracked5pider** [comment]
Should be fixed in commit: [db8c75f](https://github.com/HavocFramework/Havoc/commit/db8c75f2510096d848999889f03263013eab3120)
