### ISSUE TITLE
[File a bug report for the Demon Implant]: proc list

### ISSUE THREAD

**Issue by rhakb** [HavocFramework/Havoc#180]
### What happened?

![5](https://user-images.githubusercontent.com/22503688/196313619-3fa016be-a1bc-463a-8923-d7e51610200f.png)

Output username of "proc list"  and "shell tasklist /v" are different

bug in  Command.c#L587

`Instance->Syscall.NtOpenProcess( &hProcess, PROCESS_ALL_ACCESS, &ObjAttr, &ClientID );`

PROCESS_ALL_ACCESS is not best 

change it to
PROCESS_QUERY_LIMITED_INFORMATION (>Windows Server 2003 and Windows XP)
or
PROCESS_QUERY_INFORMATION(= Windows Server 2003 and Windows XP)

### Did You Do a Pull First?

Latest (You performed a pull first)

### Did You Read Over Your Issue First?

- [x] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by Cracked5pider** [comment]
I see thanks a lot for opening this issue.

**Comment by Cracked5pider** [comment]
fixed in commit: 4a41e858cb86431b69796f10e641e78a0db00b0e
