### ISSUE TITLE
about installation

### ISSUE THREAD

**Issue by adminsec5247** [HavocFramework/Havoc#182]
### What is the idea?

You should convert the teamserver to C++

### Is_it_already_in?

No (You checked and it doesn't.)

### Relevant code samples

```shell
God, this installation is driving me crazy
```

### Are-You-Trolling?

- [X] I declare I made an effort and provided the necessary information for an understanding of the feature by the Framework authors.

**Comment by Cracked5pider** [comment]
Why should I put extra time and energy into rewriting my server in C++. 
I have literally no reason to do so. Just because you fail to fail to install the dependencies/teamserver?
This is dumb. Never use Havoc again please thx.

**Comment by adminsec5247** [comment]
Bro, I'm sorry for what I said in the last issue, but I definitely have no other meaning. I hope you don't misunderstand me.

**Comment by CodeXTF2** [comment]
![image](https://user-images.githubusercontent.com/29991665/196779852-f652708f-5341-4d38-bed6-89ed7bfba082.png)
LMAO
