### ISSUE TITLE
[File a bug report for the Demon Implant]: GetCurrentDirectoryW for ProcessCreate. Windows Server 2012 R2 doesn't run demon agents.

### ISSUE THREAD

**Issue by rhakb** [HavocFramework/Havoc#183]
### What happened?

1: when use token impersonate, Shell command environment directories  is change to c:\windows\system, Not even with CD

you can use GetCurrentDirectory (or GetCurrentDirectoryW) to change CreateProcessWithLogonW 9th parameter

2 I can't run demon with system on Windows servr2012 r2, It will auto exit(but i use windows10 and server2019 not have this problem)
![182238](https://user-images.githubusercontent.com/22503688/196667361-bdc9d9b7-35ce-4005-b4bd-ea25eb4118df.png)

### Did You Do a Pull First?

Latest (You performed a pull first)

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by Cracked5pider** [comment]
Thanks for reporting this issue to me and explaining the steps to reproduce it. I am going to take a look into this and fix it.

**Comment by Cracked5pider** [comment]
Alright sorry for the late response but after investigating this issue it didn't crash on my win server 2012 machine. Do you mind running it under a debugger (x64dbg preferred) and sending me some screenshots (assembly instructions, stack, registers, etc.)

**Comment by rhakb** [comment]
我重新检查了它，它现在可以工作了，但现在它有随机退出，（似乎只在系统帐户中），如果我有时间
，我会详细检查它，例如使用令牌模拟然后使用 cd c：\然后使用其他命令或使用“cd c：\users”，结束不添加“\”，然后多次使用其他命令

**Comment by rhakb** [comment]
I rechecked it, it can work now, but now it have random exit,(It seems only in the system account), I'll check it in detail if I have time
such as use "token impersation' ,and then use "cd c:\" ,and then use other command
or use "cd c:\users",end not add "\",then use other command several times
