### ISSUE TITLE
[File a bug report for the Demon Implant]: Implant crashes on 2nd download command

### ISSUE THREAD

**Issue by muhyuddin** [HavocFramework/Havoc#188]
### Contact Details

rgmd777@gmail.com

### What happened?

The first download works fine and downloads the file, after that all exec commands still work. But the moment the download command is given 2nd time, the implant crashes. (sometimes crashes on the first download as well)
![image](https://user-images.githubusercontent.com/34711191/197085308-dfe810df-b423-48f9-9ab7-6aafd36435eb.png)

### Did You Do a Pull First?

Latest (You performed a pull first)

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by Cracked5pider** [comment]
Thank you so much for opening this issue. Can you reproduce this issue while enabling the debug dev flag on the teamserver 
`--debug-dev`. After enabling it recompile the agent and send me the agent debug output after crashing. Thanks

**Comment by a1dn** [comment]
I've been having the same issue. Attempting to download a file also seems to write a new file in the location with random characters at the end. Here is the output with --debug-dev enabled along with the files that were written.
![image](https://user-images.githubusercontent.com/74276204/198891617-e68cd40c-cf8e-4460-a387-6c0d62796110.png)

**Comment by Cracked5pider** [comment]
Thank you so much for providing me with enough information. I am going to investigate that issue.

**Comment by Cracked5pider** [comment]
Thank you again for reporting it to me. It should be resolved now. Please check and close this issue if its working.

**Comment by Cracked5pider** [comment]
should be fixed in [d98f8b6](https://github.com/HavocFramework/Havoc/commit/d98f8b692b9c0fe79b6d153b6f34167589082789)
