### ISSUE TITLE
[File a bug report for the Demon Implant]: Windows Defender is detecting the payload 

### ISSUE THREAD

**Issue by TanmoyG1800** [HavocFramework/Havoc#189]
### What happened?

Windows Defender is detecting the payload.
![2022-10-21 20_53_41-Window](https://user-images.githubusercontent.com/106038605/197232518-6e92e505-8421-482d-859e-20e65f747536.png)

**Comment by TanmoyG1800** [comment]
Windows Defender is detecting

**Comment by Cracked5pider** [comment]
Ok.
