### ISSUE TITLE
Upload issues in kali

### ISSUE THREAD

**Issue by Ziggrath** [HavocFramework/Havoc#190]
![unknown-1.png](https://user-images.githubusercontent.com/101295496/197266708-46f03eaf-0e6d-4e16-9d1e-1ac496b7cd76.png)
Also when trying to upload a text file with proper syntax it does nothing no errors or anything

**Comment by Cracked5pider** [comment]
This is an issue with Kalis's default Font. I can't change the default font on kali with the one that Havoc ships. The only options are using ubuntu based operating system or simply ignoring it. Can't really fix it. Or well I try to fix it. Let's see.
