### ISSUE TITLE
Payloads crash if server is restarted after crash

### ISSUE THREAD

**Issue by InfosecWestwood6969** [HavocFramework/Havoc#199]
### Contact Details

infosecwestwood6969@gmail.com

### What happened?

If the server crashes and is started again, existing agents dont connect back and the agents crash. Creates a problem of losing all agents as the teamserver is not stable enough itself and if havoc crashing (which it does a lot, as there are command parsing issues. Invalid sub-commands cause server to crash) and I lose all initial access.

### Did You Do a Pull First?

Latest (You performed a pull first)

### Relevant log output

```shell
No logs as the agent crashes. can share agent sample if needed
```

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by Cracked5pider** [comment]
Hey thank you so much for opening this issue. Havoc is still in early development and would be happy to know where exactly it crashes instead of just telling me it's crashing (like providing any screenshots of the teamserver crashing, the exact commands you passed to make the client crash, etc.).

**Comment by rhakb** [comment]
I rechecked it, it can work now, but now it have random exit,(It seems only in the system account), I'll check it in detail if I have time
such as use token impersonate and then use cd c:\ and then use other command 
or use "cd c:\users",End not added “\”，then use other command several times
