### ISSUE TITLE
[Teamserver-Client--Bug]:  Screenshot command causes the TeamServer to crash

### ISSUE THREAD

**Issue by Arokota** [HavocFramework/Havoc#204]
### What happened?

Teamserver crashes after running the `screeenshot` command.  Hangs for about 60 seconds but then eventually the client "loses" connection and the Teamserver dies.   Was able to reproduce these three times in a row.

### Did You Do a Pull First?

Latest (You performed a pull first)

### Relevant log output

```shell
zsh: killed   ./teamserver server --profile ./profiles/http_smb.yoatl -v --debug
```

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by Cracked5pider** [comment]
Alright thank you so much for opening this issue.

**Comment by Cracked5pider** [comment]
Alright tried to reproduce this problem. Do you mind sharing the whole teamserver log? Again thanks for reporting this issue to me. And be sure to have the latest commit.

**Comment by Arokota** [comment]
Sorry for the late response. You are very quick to respond :)

1. Pulled the latest commit
2. Rebuilt TeamServer and Client
3. Executed demon.exe  on Windows 10 20H2 (19042.2130) and received callback
4. Executed `whoami` which was successful
5. Executed `screenshot` which was not (See image below)


[Here](https://transfer.sh/EhtUvS/logfile.txt) is the output from the TeamServer log since it is quite long.


![image](https://user-images.githubusercontent.com/21225648/199602863-ac395fd5-c7c5-4ab9-9e56-c5d7d6f57f7a.png)

**Comment by Cracked5pider** [comment]
Thank you very much for providing me your log file. Going to take a look into it.

**Comment by S4ntiagoP** [comment]
this appears to be working fine now, reopen if needed
