### ISSUE TITLE
[Teamserver-Client--Bug]: k

### ISSUE THREAD

**Issue by otfzzz** [HavocFramework/Havoc#212]
### Contact Details

botwarzz@hotmail.com

### What happened?

Actually i tried to interact with the client computer which is my vm but it wasn't sending response, i uploaded a picture below for any help as well, i hope someone can help on this.. 

thanks

![Screenshot 2022-11-01 043635](https://user-images.githubusercontent.com/117170274/199225032-827a461b-52b9-4275-8f45-9764a70334f2.png)

### Did You Do a Pull First?

Latest (You performed a pull first)

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by Cracked5pider** [comment]
It died. As you can see in the last callback is 19min+

**Comment by otfzzz** [comment]
how do I trigger it to get active if it doesn't respond ? 

One more thing when ever the connection cut out I don't get access to the client machine 

I tried connecting to same port I used to build and test the Payload but it didn't send report , I had to click the payload again on the victims machine b4 it reported back 

Does it means the payload can't update on startup it self ?

**Comment by otfzzz** [comment]
> It died. As you can see in the last callback is 19min+




how do I trigger it to get active if it doesn't respond ?

One more thing when ever the connection cut out I don't get access to the client machine

I tried connecting to same port I used to build and test the Payload but it didn't send report , I had to click the payload again on the victims machine b4 it reported back

Does it means the payload can't update on startup it self ?

**Comment by otfzzz** [comment]
Ok thank you very much
But this tool it awesome and we need more and more great people like you 🫡🫡🫡
