### ISSUE TITLE
[Teamserver-Client--Bug]: Downloading no existing file will result on weird file created on target machine  

### ISSUE THREAD

**Issue by raf181** [HavocFramework/Havoc#215]
### Contact Details

school181@protonmail.com

### What happened?

Downloading no existing file will result in the weird file created on the target machine 
Issues continued from #193 

![image](https://user-images.githubusercontent.com/93051606/199428444-e54af4e7-4f6a-4408-9620-a48edd766ac9.png)

### Did You Do a Pull First?

Latest (You performed a pull first)

### Relevant log output

```shell
no output collected yet will update later
```

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by T1Cr4azy** [comment]
I don't know if this can help, but I tested the download with administrative privileges and it worked!

but without administrative privileges I have the same problem as the friend above!
![report](https://user-images.githubusercontent.com/85311985/199622912-f85bc1dc-092f-4a7a-8680-ed61609e4c6e.png)

**Comment by Cracked5pider** [comment]
Alright thanks for letting me know.

**Comment by Cracked5pider** [comment]
I failed to reproduce the error. Can you provide more info ? like what system (windows build number etc.)
![image](https://user-images.githubusercontent.com/51360176/199860594-4c68b65f-8a3b-4efb-ae64-9259d3d373cc.png)

**Comment by Cracked5pider** [comment]
should be fixed in [d98f8b6](https://github.com/HavocFramework/Havoc/commit/d98f8b692b9c0fe79b6d153b6f34167589082789)

**Comment by raf181** [comment]
Thanks just started setting up the new havoc update
