### ISSUE TITLE
If you fail to compile a payload, you can't generate another one without restarting Teamserver

### ISSUE THREAD

**Issue by t3hbb** [HavocFramework/Havoc#217]
### What happened?

When changing some of the underlying code (in this case trying to make a change to WinUtils.c) and go to generate a payload, if there is an error in the C code then it will fail to compile (as expected). 

However even if you go back and fix the error, from then on clicking on Generate (either in the same payload window or closing it and re-opening it via attack -> payload) doesn't appear to do anything.

Kind of related - even when I have working code in WinUtils.c, the changes don't seem to be reflected in the generated executable. I noticed that Defender was flagging on the LdrFunctionAddr function so was changing the code it flagged on 

```
        FunctionName = ( PCHAR ) Module + AddrOfNames[ i ];
        if ( HashStringA( FunctionName ) == FunctionHash )
```
        
What should I be doing to customise the output?

Thanks

### Did You Do a Pull First?

Latest (You performed a pull first)

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by S4ntiagoP** [comment]
fixed on dev
