### ISSUE TITLE
[File a bug report for the Demon Implant]: `upload` doesn't upload 20mb+ files. 

### ISSUE THREAD

**Issue by Jhinxs** [HavocFramework/Havoc#218]
### Contact Details

jhinxs@protonmail.com

### What happened?

A bug happened on upload a big file

i have been test  upload a file maby 20mb, and beacon is dead , you must need reboot server ,will get new beacon 

### Did You Do a Pull First?

Anything else (You didn't pull...)

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by Cracked5pider** [comment]
Thanks for reporting it to me. I am aware of this issue and currently rewriting upload/download features to send/receive chunked data.

**Comment by S4ntiagoP** [comment]
This should work now on the `dev` branch. Reopen if needed.
