### ISSUE TITLE
[File a bug report for the Demon Implant]: Demon keeps crashing 

### ISSUE THREAD

**Issue by raf181** [HavocFramework/Havoc#219]
### Contact Details

school181@protonmail.com

### What happened?

The demon keeps crashing ( Its detected by defender but I have also tested it with defender disabled ) Demon will run for 20s and then crash.

1. creates demon with default settings
2. transfers demon thru sftp
3. run demon (both as admin and standard permissions)
4. demon will check in and connect to the team server
5. will try to send a command to demon (has crashed before sending output)  

### Did You Do a Pull First?

Latest (You performed a pull first)

### Relevant log output

```shell
no output was collected (just demon check-in)
```

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by Cracked5pider** [comment]
Can you compile the agent in debug mode and send me the console log from it? Thanks for reporting it to me.

**Comment by jacklolidk** [comment]
having the same problem, how do you compile it in debug mode?

**Comment by raf181** [comment]
./teamserver server --profile profiles/havoc.yaotl --debug

**Comment by jacklolidk** [comment]
not the server

**Comment by jacklolidk** [comment]
you (and me) are talking about the payload/exe file that drops

**Comment by raf181** [comment]
if you compile a demon with the server running on debug mode, when you run the demon the debug dialog will appear on the target machine

**Comment by Cracked5pider** [comment]
if you wanna compile the agent in debug mode set the `--debug-dev`. 
Example: `./teamserver server --profile profiles/havoc.yaotl --debug.dev`

**Comment by cjzh781119** [comment]
demon will crash after server close

**Comment by cjzh781119** [comment]
![Screenshot from 2022-11-27 21-37-58](https://user-images.githubusercontent.com/30364306/204138344-57e10bd3-29cd-46cd-aa51-406f36be265f.png)

**Comment by Cracked5pider** [comment]
do you mind running it under a debugger (x64dbg)? 
And send me where exactly it crashes and what exactly you get as an exception.

**Comment by cjzh781119** [comment]
i got it ,when the host down and Host-Next is null ,it will crash
![Screenshot from 2022-11-27 22-22-08](https://user-images.githubusercontent.com/30364306/204140212-93c84d56-1c59-4f6b-b2cc-c275881be83e.png)

**Comment by cjzh781119** [comment]
i think "Host->Next!=NULL" is necessary


for ( Count = 0; Count < HostCount();  )
        {
            /* if the host is dead (max retries limit reached) then continue */
            if ( Host->Dead && Host->Next!=NULL){
                //PRINTF( "Host : %p (%ls:%ld :: Dead[%s] position1:: Failures[%d])\n", Host, Host->Host, Host->Port, Host->Dead ? "TRUE" : "FALSE", Host->Failures )
                Host = Host->Next;}
            else break;
        }

**Comment by Cracked5pider** [comment]
this issue was fixed in commit [fba842f](https://github.com/HavocFramework/Havoc/commit/fba842ff68d0dc7a476d48129d063ecbd84e8c2e)
reopen or let me know if it still persists.
