### ISSUE TITLE
[Teamserver-Client--Bug]: Building Demon with multiple Headers and Uri doesn't call back

### ISSUE THREAD

**Issue by dmcxblue** [HavocFramework/Havoc#220]
### What happened?

A bug happened!

Giving Havoc multiple headers does not call back to C2, I've tried editing the predefined profiles but still with no luck. Also every time I build an HTTP Listener it still calls it an HTTPS protocol?

![image](https://user-images.githubusercontent.com/41899653/200007010-ac50b4ca-fa10-42ce-a76e-644365bb9995.png)

![Havoc-ProfileTest](https://user-images.githubusercontent.com/41899653/200008877-39914af9-f7f6-4796-9352-932c13763054.gif)

### Did You Do a Pull First?

Latest (You performed a pull first)

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by Cracked5pider** [comment]
Do you mind compiling the agent in debug mode and sending me the console log from the agent? And thanks for reporting it to me.

**Comment by dmcxblue** [comment]
My Error, I was adding the Host Header.
