### ISSUE TITLE
[Teamserver-Client--Bug]: Wrong Payload showing in Menu

### ISSUE THREAD

**Issue by dmcxblue** [HavocFramework/Havoc#221]
### What happened?

A bug happened!

Wrong payload showing in the configuration

![image](https://user-images.githubusercontent.com/41899653/200024587-40da7abf-06f1-4903-b8cf-4af0bae1a7e6.png)

### Did You Do a Pull First?

Latest (You performed a pull first)

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by Cracked5pider** [comment]
fixed in [d98f8b6](https://github.com/HavocFramework/Havoc/commit/d98f8b692b9c0fe79b6d153b6f34167589082789)
