### ISSUE TITLE
[File a bug report for the Demon Implant]: 

### ISSUE THREAD

**Issue by dmcxblue** [HavocFramework/Havoc#224]
### What happened?

A bug happened!

User Agent not applied when starting the listener, viewed with Wireshark this happens and both HTTP/HTTPS protocols.

USER-AGENT
![image](https://user-images.githubusercontent.com/41899653/200094506-82a352c7-4416-4e3a-8764-6530d81c7a3f.png)

Debug Implant

![image](https://user-images.githubusercontent.com/41899653/200094539-8e5f2859-3c51-4df5-bb97-83c4e8669966.png)

### Did You Do a Pull First?

Latest (You performed a pull first)

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by Cracked5pider** [comment]
Alright thanks for letting me know.

**Comment by Cracked5pider** [comment]
Should be fixed in [133f6ea](https://github.com/HavocFramework/Havoc/commit/133f6ead8085147dc39beb368c41aead2873927e)
