### ISSUE TITLE
[File a bug report for the Demon Implant]: token

### ISSUE THREAD

**Issue by rhakb** [HavocFramework/Havoc#228]
### What happened?

domon initial permission is system, token 0 is administrator(name show error), and function have bug
![c](https://user-images.githubusercontent.com/22503688/202071974-882a74d0-abd1-4178-a621-1a3bc3909094.png)

### Did You Do a Pull First?

Latest (You performed a pull first)

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by S4ntiagoP** [comment]
fixed on dev
