### ISSUE TITLE
[Teamserver-Client--Bug]:  Generating payload from directory name containing spaces

### ISSUE THREAD

**Issue by Unkn8wn69** [HavocFramework/Havoc#230]
### What happened?

When running the Client from an folder that contains spaces in the name it will interpretate those as new lines when trying to generate the payload.

Output: (Im in "/home/user/Desktop/Hacking Tools"

### Did You Do a Pull First?

Anything else (You didn't pull...)

### Relevant log output

```shell
[*] Starting build
[*] Use indirect syscalls
[*] Config size [408 bytes]
[*] Compiling source
[-] Couldn't compile implant: exit status 127
[-] Compile output: sh: Line 1: /home/user/Desktop/Hacking: File or Directory not found
sh: Line 1: Tools/Havoc/Havoc/Teamserver/data/x86_64-w64-mingw32-cross/bin/x86_64-w64-mingw32-gcc: File or Directory not found
```

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by S4ntiagoP** [comment]
fixed on dev, thanks for reporting!
