### ISSUE TITLE
[Teamserver-Client--Bug]: Security Disclosure

### ISSUE THREAD

**Issue by hyperreality** [HavocFramework/Havoc#232]
### Contact Details

hyperreality@codewordsolver.com

### What happened?

Please contact me privately so I can disclose a security vulnerability affecting the teamserver.

### Did You Do a Pull First?

Latest (You performed a pull first)

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by Cracked5pider** [comment]
Hey, you can message me over on discord `5pider#8441`. Thx for reporting it to me.

**Comment by Cracked5pider** [comment]
Thank you for reporting. Has been fixed in commit [133f6ea](https://github.com/HavocFramework/Havoc/commit/133f6ead8085147dc39beb368c41aead2873927e)
I hope I see more of your vuln reports in the future.
