### ISSUE TITLE
[File a bug report for the Demon Implant]: Proxy password options is wrong

### ISSUE THREAD

**Issue by dpakon1** [HavocFramework/Havoc#234]
### What happened?

Hello, thank you for good tool!
I found one bug in source file TransportHttp.c, when setting http proxy options (user password). Now this option is WINHTTP_OPTION_PROXY_USERNAME but need to be WINHTTP_OPTION_PROXY_PASSWORD (docs https://learn.microsoft.com/en-us/windows/win32/winhttp/option-flags)

link to source code:
https://github.com/HavocFramework/Havoc/blob/d98f8b692b9c0fe79b6d153b6f34167589082789/Teamserver/data/implants/Demon/Source/Core/TransportHttp.c#L136

### Did You Do a Pull First?

Latest (You performed a pull first)

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by Cracked5pider** [comment]
Ah thanks for pointing this out. Yeah I just copy and pasted my own code here lol. Going to fix that in the next commit.

**Comment by Cracked5pider** [comment]
Thanks for reporting. Has been fixed in [133f6ea](https://github.com/HavocFramework/Havoc/commit/133f6ead8085147dc39beb368c41aead2873927e)
