### ISSUE TITLE
[Teamserver-Client--Bug]: `Install.sh` fails to properly installed MinGW

### ISSUE THREAD

**Issue by CompeyDev** [HavocFramework/Havoc#235]
### Contact Details

hi@devcomp.xyz

### What happened?

The installation script for the teamserver installs a version of MinGW which does not include the `i686-w64-mingw32-gcc` executable, and as a result the teamserver panics. This can be fixed by manually installing MinGW, rather than using the Install.sh script. 

### Did You Do a Pull First?

Latest (You performed a pull first)

### Relevant log output

```shell
_______           _______  _______
    │\     /│(  ___  )│\     /│(  ___  )(  ____ \
    │ )   ( ││ (   ) ││ )   ( ││ (   ) ││ (    \/
    │ (___) ││ (___) ││ │   │ ││ │   │ ││ │
[10:41:37] [ERRO] Couldn't find x86 mingw compiler: exec: "i686-w64-mingw32-gcc": executable file not found in $PATH
[10:41:37] [ERRO] Please install needed packages. Refer to the Wiki for more help.
    │  ___  ││  ___  │( (   ) )│ │   │ ││ │
```

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by Cracked5pider** [comment]
you can set `i686-w64-mingw32-gcc` to any executable since the teamserver currently doesn't compile the agent to x86 binary. 
The `Compiler64` field has been added for future implementations and features. 
Gonna add the `i686-w64-mingw32-gcc` to the `Install.sh` once i added x86 support.

**Comment by CompeyDev** [comment]
> Gonna add the i686-w64-mingw32-gcc to the Install.sh once i added x86 support.

It is honestly a bit useless to have that check then (until it is supported), as it utterly confused when during the installation.
