### ISSUE TITLE
Will there be a reverse proxy?

### ISSUE THREAD

**Issue by MattPlayGamez** [HavocFramework/Havoc#241]
### Contact Details

penson.mathys@gmail.com

### What is the idea?

Dear,
Will there be a reverse proxy or support for cloudflare tunnels / ngrok?

PS. i know there is a support for socks proxy
Kind regards,
Matt

### Is_it_already_in?

No (You checked and it doesn't.)

### Are-You-Trolling?

- [X] I declare I made an effort and provided the necessary information for an understanding of the feature by the Framework authors.

**Comment by Cracked5pider** [comment]
It should support ngrok and other reverse proxies. 
You can set the host:port of your reverse proxy in the Hosts field while creating a new listener.
Try it out and let me know if you mean this. 
![image](https://user-images.githubusercontent.com/51360176/208253362-907d75fa-1f6c-46d6-b0e3-6edd1242c600.png)

**Comment by MattPlayGamez** [comment]
Dear @Cracked5pider,
Thanks for helping! It solved my issue.

Btw, It is detected by Windows AV and other AVs

Best regards,
Matt

**Comment by Cracked5pider** [comment]
Yes I am fully aware that it is getting detected by Windows Def and other AVs. Tho it's not my goal to evade them. 
Glad to hear that it resolved your issue.
