### ISSUE TITLE
[Feature Suggestions/Enhancements]: yo mama

### ISSUE THREAD

**Issue by gomep342** [HavocFramework/Havoc#242]
### What is the idea?

You *should* add release builds for major update bc all that libs takes too much for install
it's not a suggestion, it's an order.Do it.

Best regards

### Is_it_already_in?

No (You checked and it doesn't.)

### Relevant code samples

```shell
print("i retarded")
```

### Are-You-Trolling?

- [x] I declare I made an effort and provided the necessary information for an understanding of the feature by the Framework authors.

**Comment by Cracked5pider** [comment]
lol.
