### ISSUE TITLE
[Demon] Not whoami output with LOCAL SERVICE account

### ISSUE THREAD

**Issue by Atsika** [HavocFramework/Havoc#245]
### What happened?

When stealing and impersonating a token belonging to a LOCAL SERVICE account, the output of the `whoami` command is empty.

![image](https://user-images.githubusercontent.com/46649001/210374402-b8dfc935-f537-4557-bf97-2ba68b95e312.png)

However the `whoami` command works well with a classic user or even SYSTEM.

### Did You Do a Pull First?

Latest (You performed a pull first)

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by S4ntiagoP** [comment]
this seems to be working on `dev`, reopen if needed
