### ISSUE TITLE
[Teamserver-Client--Bug]: CMake Error at CMakeLists.txt:181

### ISSUE THREAD

**Issue by GitHubUserPy** [HavocFramework/Havoc#246]
### What happened?

When I run `make` it runs most commands. Until eventually (right after Found PythonLibs)
I am running Arch Linux, and have run:

 `sudo pacman -S base-devel qt5-base git cmake`

These are the necessary requisites. But I have a feeling I am missing one. 
I have looked at other questions but have not found any reasonable answer, considering I am on Arch. 

I have looked for answers but I have not found a solution for Arch Linux, sorry.

**Here is a screenshot:** 

![Screenshot from 2023-01-04 07-57-12](https://user-images.githubusercontent.com/90471685/210509339-7fee965e-2ce8-4f11-9791-8f3578397df8.png)

Thank you,

### Did You Do a Pull First?

Latest (You performed a pull first)

### Did You Read Over Your Issue First?

- [x] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by GitHubUserPy** [comment]
I understand i need to install the spdlog library, but that I do not understand how to install it in Arch Linux, which is why i was wondering if I should ask github or if I should figure it out. Sadly I cannot find any way of installing it on Arch Linux

**Comment by Cracked5pider** [comment]
on arch linux the package name should be `spdlog` which you need to install. 
I think it should work using this command. `pacman -S spdlog`

**Comment by GitHubUserPy** [comment]
Thank you very much

**Comment by GitHubUserPy** [comment]
Sorry I just was wondering, I am having the same error with Qt5, do you need a screenshot?

**Comment by FlexAirTor** [comment]
I have the same problem with Parrot Security Os, how I can fix this?

![image](https://user-images.githubusercontent.com/82037355/219446697-b9ed4299-d1fe-4e07-b9bf-4c6428a82783.png)

**Comment by gnusec** [comment]
How did you solve this problem? Thank you!  @FlexAirTor

**Comment by FlexAirTor** [comment]
> How did you solve this problem? Thank you!  @FlexAirTor 

You will not believe me, but in the end I changed the operating system for Kali Linux, at the end of all Havoc is not optimized for parrot apparently.

**Comment by Cracked5pider** [comment]
you won't believe me this but this all could have been fixed by following the documentation and like I mentioned above, installing `spdlog`.
and then delete the `Build` directory and rebuild the client.
