### ISSUE TITLE
[Feature Suggestions/Enhancements]: Automatically detect proxy settings

### ISSUE THREAD

**Issue by frantz45** [HavocFramework/Havoc#250]
### What is the idea?

It would be nice that Demon automatically detects system proxy settings.<br>
Because you can't guess if the target need a proxy or not.

### Is_it_already_in?

No (You checked and it doesn't.)

### Are-You-Trolling?

- [X] I declare I made an effort and provided the necessary information for an understanding of the feature by the Framework authors.

**Comment by nurfed1** [comment]
I attempted to implement this in https://github.com/HavocFramework/Havoc/pull/348. 
Feel free to try and let me know if there's issues.

**Comment by S4ntiagoP** [comment]
as @nurfed1 said, this is already included in main
