### ISSUE TITLE
[Teamserver-Client--Bug]: Editing/Removing A Listener

### ISSUE THREAD

**Issue by TheGrayFox92** [HavocFramework/Havoc#251]
### Contact Details

Discord : !Sam#4273

### What happened?

Once the server is up and running; if you delete, or edit the contents of a listener. (For example, amending URIs during test), the changes do not stay upon server restart. 

If you delete a listener, and restart the server, the listeners are not actually removed from the DB and the server will try and load them back into the teamserver. 

If you edit the listener, the initial configuration is added to the database, but no further changes are logged, so if you make any changes to the listener, once you restart the teamserver, it always reverts to the initial configuration. 

I'm happy to take screenshots, but it would just be windows of the origina/new listener config, restarting the server, and then the original listener config again. 

### Did You Do a Pull First?

Latest (You performed a pull first)

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by FlexAirTor** [comment]
Just delete havoc.db, the framework created again when you start the Teamserver

**Comment by S4ntiagoP** [comment]
this should now be fixed on the dev branch, thanks for reporting!
