### ISSUE TITLE
[Teamserver-Client--Bug]: 

### ISSUE THREAD

**Issue by cddsbniknf** [HavocFramework/Havoc#254]
### Contact Details

2647534839@qq.com

### What happened?

登不上

### Did You Do a Pull First?

Latest (You performed a pull first)

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by Cracked5pider** [comment]
I do not understand your issue. Unfortunately, I do not speak Chinese.

**Comment by S4ntiagoP** [comment]
closing this, reopen if needed
