### ISSUE TITLE
[File a bug report for the Demon Implant]: token bug fix

### ISSUE THREAD

**Issue by rhakb** [HavocFramework/Havoc#263]
### What happened?

sorry,I won't use pull requests

fix this bug https://github.com/HavocFramework/Havoc/issues/228

1 domain\user name show error

https://github.com/HavocFramework/Havoc/blob/dev/payloads/Demon/Source/Core/Command.c#L1309
this User is pointer, so you cannot free it

2 system cannot use administrator token to createprocess

https://github.com/HavocFramework/Havoc/blob/dev/payloads/Demon/Source/Core/WinUtils.c#L326

i view cs source , It uses CreateProcessAsUserA instead of CreateProcessWithTokenW,but use CreateProcessAsUserA ,  it like cs, the administrator cannot use any stolen token to create other process ( include system token  ,you can write a separate command for getsystem )，the system can use any stolen token 

3  Perhaps the TokenSetPrivilege function needs to be preceded by the ReverToSelf function, and then restored later 
https://github.com/HavocFramework/Havoc/blob/dev/payloads/Demon/Source/Core/WinUtils.c#L293

change to 

TokenImpersonate(FALSE);
 TokenSetPrivilege( SE_IMPERSONATE_NAME, TRUE );
TokenImpersonate(TRUE);

### Did You Do a Pull First?

Latest (You performed a pull first)

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by S4ntiagoP** [comment]
this has been fixed on dev, thank you for the fix recommendation!
