### ISSUE TITLE
[Teamserver-Client--Bug]: Beacon dies after the token make Module

### ISSUE THREAD

**Issue by MrRobot-2020** [HavocFramework/Havoc#277]
### Contact Details

mrrobot.wolf@gmail.com

### What happened?

When working on the token make command "token make domain.local user pass" after executing the command the beacon goes to dead state where there is no response from the beacon.

### Did You Do a Pull First?

Anything else (You didn't pull...)

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by S4ntiagoP** [comment]
in which branch have you tried this? `dev` seems to be working just fine

**Comment by hugojcqs** [comment]
Had the same problem in the rastalabs HTB prolab. I have not tried the dev branch just yet.

**Comment by S4ntiagoP** [comment]
thank you @hugojcqs, would you mind trying this again on `dev`?

**Comment by S4ntiagoP** [comment]
thank you @hugojcqs !
