### ISSUE TITLE
[File a bug report for the Demon Implant]: fix proc list command crash

### ISSUE THREAD

**Issue by rhakb** [HavocFramework/Havoc#279]
### What happened?

fix https://github.com/HavocFramework/Havoc/issues/274           bug 3

change
https://github.com/HavocFramework/Havoc/blob/dev/payloads/Demon/Source/Core/WinUtils.c#L184
to
*UserSize  = UserNameSize + 2 + DomainSize;

because 
"UCHAR        Deli[ 2 ]            = { '\\', 0 };"
The length of deil is 2, not 1

### Did You Do a Pull First?

Latest (You performed a pull first)

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by S4ntiagoP** [comment]
thank you!
