### ISSUE TITLE
socks not working

### ISSUE THREAD

**Issue by realalexandergeorgiev** [HavocFramework/Havoc#281]
### What happened?

socks4a server doesnt work. creates a listener on teamserver machine, but doesnt respond

[proxychains] config file found: /etc/proxychains4.conf
[proxychains] preloading /usr/lib/x86_64-linux-gnu/libproxychains.so.4
[proxychains] DLL init: proxychains-ng 4.16
[proxychains] Strict chain  ...  127.0.0.1:1081  ...  192.168.1.1:80 <--socket error or timeout!
curl: (7) Couldn't connect to server

### Did You Do a Pull First?

Latest (You performed a pull first)

### Relevant log output

```shell
16/03/2023 05:12:24 [5pider] Demon » socks list
[*] Socks proxy server: 

 Port 
 ---- 
 1081
```

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by Cracked5pider** [comment]
does your team server run on your local host?

**Comment by realalexandergeorgiev** [comment]
on a kali VM. implant on windows VM. both in lab network with internet access

**Comment by S4ntiagoP** [comment]
which branch are you using?
also, is there anything listening on 192.168.1.1:80 ?

**Comment by realalexandergeorgiev** [comment]
i cloned the repo about 1 before posting the issue (git clone https://github.com/HavocFramework/Havoc.git as mentioned in the wiki). 

yes, my routers webinterface, i verified using curl.

**Comment by n0isegat3** [comment]
hey, same issue here. tested on latest repo. teamserver on kali. demon on Windows. socks running on 4444. using proxychains socks4. tested using nmap and port 445 (target environment is AD network... 445 available from the victim to the target)...

**Comment by S4ntiagoP** [comment]
I have tested this on `dev` (which now uses socks5) and it seems to be working just fine with proxychains.

**Comment by n0isegat3** [comment]
> I have tested this on `dev` (which now uses socks5) and it seems to be working just fine with proxychains.

will give it a try. thanks!

**Comment by S4ntiagoP** [comment]
Also, if you are going to proxy DNS requests, I recommend using proxychains-ng over regular proxychains.

**Comment by S4ntiagoP** [comment]
as this is already fixed, I'm closing this. Reopen if needed.
