### ISSUE TITLE
[Teamserver-Client--Bug]: Pivot list not working

### ISSUE THREAD

**Issue by zerobytes999** [HavocFramework/Havoc#285]
### What happened?

![Screenshot_2023-03-20_16-41-54](https://user-images.githubusercontent.com/61564840/226409112-1282e83d-3641-4e8d-b975-26b515850b2f.jpg)

in the above picture, i had three demons:

HTTPS <---> SMB <--> SMB

I executed pivot list on the https endpoint, the behavior was when the command is sent, nothing happens for 30 seconds - during the wait, the demons disconnect, when the 30 seconds pass, the demons connect back and still without results. I tried other commands like ipconfig and it works properly

### Did You Do a Pull First?

Anything else (You didn't pull...)

### Relevant log output

```shell
20/03/2023 16:26:49 [5pider] Demon » pivot list
[*] [7FD139E2] Tasked demon to list connected agent pivots
[+] Send Task to Agent [12 bytes]

20/03/2023 16:28:23 [5pider] Demon » pivot list
[*] [E2FC0549] Tasked demon to list connected agent pivots
[+] Send Task to Agent [12 bytes]
```

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by S4ntiagoP** [comment]
this works on `dev`, reopen if needed.
