### ISSUE TITLE
[Teamserver-Client--Bug]: 

### ISSUE THREAD

**Issue by mrx325** [HavocFramework/Havoc#286]
### What happened?

Havoc client crashes while executing get-netsession 

### Did You Do a Pull First?

Latest (You performed a pull first)

### Relevant log output

```shell
18:07:07] [info] Started "local" listener
zsh: segmentation fault  ./Havoc
```

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by S4ntiagoP** [comment]
works on `dev`
