### ISSUE TITLE
[Teamserver-Client--Bug]: 

### ISSUE THREAD

**Issue by LucasIsRed** [HavocFramework/Havoc#287]
### Contact Details

Galaxy6239@protonmail.com

### What happened?

When trying to build Client with "make", it errors.

### Did You Do a Pull First?

Latest (You performed a pull first)

### Relevant log output

```shell
mkdir: cannot create directory ‘Build’: File exists
/bin/sh: 1: cmake: not found
make: *** [makefile:8: all] Error 127
```

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by S4ntiagoP** [comment]
this works on `dev`
