### ISSUE TITLE
dotnet inline-execute limited payload size over SMB namedpipe pivot

### ISSUE THREAD

**Issue by hugojcqs** [HavocFramework/Havoc#293]
### What happened?

Hello,

This was tested on the DEV branch, that last commit used is: 146c7835e70a143305ca5d4e0e6f5112a13238b4

When using something like:

`TS <--HTTPS--> Beacon1 <--SMB--> Beacon2`

And trying to execute C# using `dotnet inline-execute sometools.exe`, if the size of the tool is too great the command fails but does not provide any more information other than the number of bytes sent to the beacon. Please note the exact same command work on the first beacon. 

The sleep time is set to 2 seconds with no jitter on both beacon.

Thank you for the great work ! 😄 

### Did You Do a Pull First?

Anything else (You didn't pull...)

### Relevant log output

```shell
[13:42:18] [DBUG] [server.(*Teamserver).DispatchEvent:206]: Prepare command for pivot demon: 2b7b67d0
[13:42:19] [WARN] Agent: 15d26e04, CommandID: 91, unknown RequestID: 0. This is either a bug or malicious activity
```

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by S4ntiagoP** [comment]
Thanks for reporting! I will take a look at this later, sounds like a hiccup on the protocol

**Comment by S4ntiagoP** [comment]
Ok, this should work now. Please reopen if it still fails, bugs are to be expected with a change like this one.

**Comment by hastalamuerte** [comment]
[WARN] Agent: 1435abb0, CommandID: 2510, unknown RequestID: 60d4b872. This is either a bug or malicious activity
[WARN] Agent: 1435abb0, CommandID: 2510, unknown RequestID: 60d4b872. This is either a bug or malicious activity

got same when trying take a screenshot - after it demon became unresponsible
