### ISSUE TITLE
[File a bug report for the Demon Implant]: 

### ISSUE THREAD

**Issue by cerealbocks** [HavocFramework/Havoc#302]
### Contact Details

privacycabinet@gmail.com

### What happened?

My host machine is Ubuntu and my VM is Windows 10, with a bridged adapter. I served the .exe demon implant (default config.) to myself and it's now on my VM. Problem is, when I try to run it, I get no callback. I took a look in Wireshark on my host VM, and was confused to discover that when I attempt to run the demon, my VM initiates a handshake with 20.42.73.29, which is acknowledged. This IP address resolves to some kind of Telemetry service. I pulled the below blob out of the ascii representation of the Wireshark traffic.

Washington10URedmond10U
Microsoft Corporation1200U)Microsoft Root Certificate Authority 20110
111018225519Z
261018230519Z0~10	UUS10U
Washington10URedmond10U
Microsoft Corporation1(0&UMicrosoft Secure Server CA 20110"0

Disabling the Firewall and Defender didn't change anything. Please let me know if you have any ideas as to what's going on, and what more information you need from me specifically. Thanks.

### Did You Do a Pull First?

Latest (You performed a pull first)

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by 0xv1n** [comment]
Looks like a Watson IP, which normally gets contacted when an application crashes. Is your Win10 machine 64 bit? Have you looked at task manager to see if the agent is actually running?

**Comment by cr7pt0pl4gu3** [comment]
@0xv1n @cerealbocks I can confirm that I've had a similar issue when the implant runs (and shows in taskmgr) but doesn't connect to the listener (with no Wireshark traffic at all).

There is a temporary workaround - enabling proxy and setting same address as the listener:
![image](https://github.com/HavocFramework/Havoc/assets/43863412/de21c99a-6375-4052-9c12-1be24af4e8f1)
