### ISSUE TITLE
[File a bug report for the Havoc Framework Documentation]: How to use 3rd party agent 

### ISSUE THREAD

**Issue by Ericxu833** [HavocFramework/Havoc#313]
### What's the issue?

How to use 3rd party agent .
I can't get useful information in Documentation.
Copy which files to where , or edit witch profiles.
TNX.

### Did You Do a Pull First?

Latest (You performed a pull first)

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for identification and remediation of the issue.

**Comment by Cracked5pider** [comment]
https://codex-7.gitbook.io/codexs-terminal-window/red-team/red-team-dev/extending-havoc-c2/third-party-agents
