### ISSUE TITLE
[Teamserver-Client--Bug]:  Unabale to build the team server

### ISSUE THREAD

**Issue by kali64amd** [HavocFramework/Havoc#316]
### Contact Details

kali64amd@gmail.com

### What happened?

I'm not able to build team server why? Please have look this and advice me Appreciate your help.

 
![Team1](https://user-images.githubusercontent.com/28497075/234389467-f412f1e2-4217-4b95-99c4-dd3ecf3ac3f2.png)

### Did You Do a Pull First?

Latest (You performed a pull first)

### Did You Try With the Dev Branch?

Yes (You tried using the dev branch but the problem persist)

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by S4ntiagoP** [comment]
You are inside the _teamserver_ directory, run it on the root dir of havoc. Reopen if needed.

**Comment by S4ntiagoP** [comment]
cool username btw lol
