### ISSUE TITLE
[Teamserver-Client--Bug]: Unabale to build the team server #316

### ISSUE THREAD

**Issue by kali64amd** [HavocFramework/Havoc#317]
### Contact Details

kali64amd@gmail.com

### What happened?

strange!! nothing build up ...  (didn't find ./teamserver.sh in teamserver DIR)

![make1](https://user-images.githubusercontent.com/28497075/234399926-8168d9a6-07aa-4a08-8ba8-de4ef6ca324c.png)

### Did You Do a Pull First?

Latest (You performed a pull first)

### Did You Try With the Dev Branch?

Yes (You tried using the dev branch but the problem persist)

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by Cracked5pider** [comment]
looks like it is already built lmao.

**Comment by kali64amd** [comment]
couldn't find teamserver file in teamserver DIR

And I have checked in also client DIR...... nothing!!!

So where it's build up?????

**Comment by kali64amd** [comment]
OK!! .........................Now Client Collapse!!!!

![client](https://user-images.githubusercontent.com/28497075/234559351-450f2dc5-782a-4e21-b294-a2bb65a66572.png)
![server](https://user-images.githubusercontent.com/28497075/234559371-475aac78-6826-444e-84e6-91de43029ac4.png)

**Comment by kali64amd** [comment]
OK, I have fix it!!!


Appreciate your help guys...............

**Comment by Cracked5pider** [comment]
you are doing it wrong. you need to use the `./havoc client` to execute the gui client.
