### ISSUE TITLE
[Teamserver-Client--Bug]: 

### ISSUE THREAD

**Issue by 0xv1n** [HavocFramework/Havoc#318]
### What happened?

Some condition is causing the Listener config to set `PortConn` to an empty string. This causes errors when attempting to generate payloads since `strconv.Atoi(PortConn)` when `PortConn` is an empty string, will throw an error. 

When reading the Listener config from DB, we should ensure that both values are valid integers, and `PortConn` should always fall back on `PortBind` if the value is not a valid int. This should fix that issue. 

I'm not sure if we need to add this to:

`client/Source/UserInterface/Widgets/ListenersTable.cpp`, or
`client/Source/UserInterface/Dialogs/Listener.cpp` or potentially somewhere else.

Should be an easy fix, will look into it this weekend unless @S4ntiagoP / @Cracked5pider get to it first.

### Did You Do a Pull First?

Latest (You performed a pull first)

### Did You Try With the Dev Branch?

Yes (You tried using the dev branch but the problem persist)

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by Cracked5pider** [comment]
I am gonna fix this in the following commits.

**Comment by 0xv1n** [comment]
Closed by https://github.com/HavocFramework/Havoc/commit/6c1f6e539bd1e9ac9500b183d6762cbbc575b9e4#diff-28ede3d7bd4d5002a6986f16041c3c9a908e32f679616e36013a7dd6b682a0b8
