### ISSUE TITLE
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 5939, resource id: 11439287, major code: 40 (TranslateCoords), minor code: 0[File a bug report for the Demon Implant]: 

### ISSUE THREAD

**Issue by Cyberchunk87** [HavocFramework/Havoc#321]
### Contact Details

irfan.butt@live.com

### What happened?

my payload is unable to establish contact with team server listener...
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 5939, resource id: 11439287, major code: 40 (TranslateCoords), minor code: 0

### Did You Do a Pull First?

Latest (You performed a pull first)

### Did You Try With the Dev Branch?

Yes (You tried using the dev branch but the problem persist)

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by Cracked5pider** [comment]
This error message can be ignored. 
Your payload not being able to connect is another issue. Do you mind providing more info?

**Comment by Cyberchunk87** [comment]
Ifconfig
[cid:1119a90b-be4a-44c4-8e3c-a937f21bc47f]
My Profile Settings::>>>
[cid:bb55ce29-bd43-4260-a5b6-6b9381e66838]

Team Server Enabled?>>>
[cid:209f4ac1-043f-4ad4-9c84-c61876d7314f]
Connection to Client?>>>
[cid:a4cd394c-509f-48b5-9adb-e227045303e6]
[cid:e0bd549d-0191-4907-8b01-99c98653d05d]payload generation>>>>
[cid:68bfcd67-49c9-47a7-8517-b2205db71365]
Tgt Pc connectivity test
[cid:7345b36c-3184-4b12-8f27-9ef7a9037017]
Listener view
[cid:a0a60954-0539-4d60-bd2c-f13cf1eb5163]
Payload exe
[cid:e785965c-34c5-4b63-ae29-4903c6681387]
But connection of listener not established
[cid:03f6e352-e349-466d-b796-26e600fa4fff]
Please Advice

**Comment by Cracked5pider** [comment]
I can't read anything you just send.
