### ISSUE TITLE
go: cannot match "golang.org/x/sys" without -versions or an explicit version

### ISSUE THREAD

**Issue by Ericxu833** [HavocFramework/Havoc#328]
### What's the issue?

$ go version
go version go1.18.1 linux/amd64

### Building the Teamserver

Install additional Go dependencies:

$ go mod download golang.org/x/sys
go: cannot match "golang.org/x/sys" without -versions or an explicit version: go.mod file not found in current directory or any parent directory; see 'go help modules'

$go mod download github.com/ugorji/go
go: cannot match "github.com/ugorji/go" without -versions or an explicit version: go.mod file not found in current directory or any parent directory; see 'go help modules'

### Instead following steps,works
go get -u golang.org/x/sys 
go get github.com/ugorji/go/codec

### Did You Do a Pull First?

Latest (You performed a pull first)

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for identification and remediation of the issue.

**Comment by Cracked5pider** [comment]
golang installs required dependencies by themselves while preparing & compiling the teamserver. so no need to install them yourself using `go mod download ...` 
imma update the wiki soon for this.
