### ISSUE TITLE
[Feature Suggestions/Enhancements]: Loot folders as dates only (not including hours and minute markers)

### ISSUE THREAD

**Issue by sro-nviso** [HavocFramework/Havoc#337]
### Contact Details

steffen.rogge@nviso.eu

### What is the idea?

I downloaded a few files in a lab yesterday and the loot folder on the Teamserver has subfolders based on the day, but sadly the folder name also includes the hours and minute.
This is confusing, since all files downloaded on that day land in that folder.

So a folder called "05.05.2023 17:10" would still be the folder even if you download files at 18:46.

So maybe use just the date as the folder name would be enough as it has the same outcome?

### Is_it_already_in?

No (You checked and it doesn't.)

### Are-You-Trolling?

- [X] I declare I made an effort and provided the necessary information for an understanding of the feature by the Framework authors.

**Comment by S4ntiagoP** [comment]
including the time is required because you can run the server multiple times on a single day, the time is set by the time on which the server was started
