### ISSUE TITLE
[Feature Suggestions/Enhancements]: 

### ISSUE THREAD

**Issue by 0xb000bd** [HavocFramework/Havoc#339]
### What is the idea?

I wonder why the python version must be exactly 3.10? I update my Arch machine, python is updated to python 3.11, then I cannot build Havoc. I don't want to create virtual machine, so I hope you can make it be available for recent versions of python

### Is_it_already_in?

No (You checked and it doesn't.)

### Are-You-Trolling?

- [X] I declare I made an effort and provided the necessary information for an understanding of the feature by the Framework authors.

**Comment by Cracked5pider** [comment]
In Python 3.11 there are some API changes (API function renames). So we either use Python 3.10 or Python 3.11. 
But it has been fixed already the dev branch so please check it out and let me know if it's working.
