### ISSUE TITLE
[Teamserver-Client--Bug]: Invalid C++ syntax causing GCC build failure

### ISSUE THREAD

**Issue by gmorpheme** [HavocFramework/Havoc#347]
### Contact Details

@gmorpheme

### What happened?

The following lines in DemoCmdDispatch have an unnecessary and illegal "CommandExecute::" qualifier on their member function declarations which apparently VisualStudio ignores but which causes build failures on GCC. Removing the qualifier fixes the build.

(https://github.com/HavocFramework/Havoc/blob/edaa969695d4bd08b0801c3215596be534cf1b45/client/Include/Havoc/DemonCmdDispatch.h#L75-L77)

These errors are actually visible but buried in quite a lot of other problems in #322 so you could regard this as a duplicate, but not sure anyone's noticed them there.

### Did You Do a Pull First?

Latest (You performed a pull first)

### Did You Try With the Dev Branch?

Yes (You tried using the dev branch but the problem persist)

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by ScRiPt1337** [comment]
i am also having the same issue when i am trying to compile the client

**Comment by gmorpheme** [comment]
Apologies - misunderstood dev branch. Have verified it's fixed on dev.

**Comment by winterrdog** [comment]
Then it'd a good time to close the issue 🙂
