### ISSUE TITLE
[Teamserver-Client--Bug]: Teamserver ignores "X-Forwarded-For" header

### ISSUE THREAD

**Issue by GreyHatCyberSecurity** [HavocFramework/Havoc#351]
### Contact Details

greyhatfeedback@protonmail.com

### What happened?

When using redirectors with Havoc C2, it became necessary to see the IP address of the connection initializer rather than the IP address of the redirector the beacon came from.

The redirectors were configured to pass all the headers along with the HTTP packet

In the havoc profile settings, the TrustXForwardedFor variable was set to `true`.

![image](https://github.com/HavocFramework/Havoc/assets/89209437/0b1896c1-f479-45f1-ba99-450623074c2a)

Teamserver ignores the X-Forwarded-For header and displays the redirector IP address, although when a packet is normally sent to my C2 server, the X-Forwarded-For header is present

When I send curl myredirector:80 and turn on C2 listening, a packet like this arrives, which has all the necessary headers. But Havoc ignores them.
![image](https://github.com/HavocFramework/Havoc/assets/89209437/876f54c8-1a32-4a40-bdff-2d78b0a7f1a7)

To redirect the packet I use nginx as a proxy

### Did You Do a Pull First?

Latest (You performed a pull first)

### Did You Try With the Dev Branch?

Yes (You tried using the dev branch but the problem persist)

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by S4ntiagoP** [comment]
fixed on `dev`, if still an issue, please reopen.
thank you for reporting!
