### ISSUE TITLE
[Teamserver-Client--Bug]: Make client-build error

### ISSUE THREAD

**Issue by raf181** [HavocFramework/Havoc#354]
### What happened?

Error creating client, found these error with main branch but some how it fixed it self but im not able to replicate the steps to fix it

### Did You Do a Pull First?

Latest (You performed a pull first)

### Did You Try With the Dev Branch?

Yes (You tried using the dev branch but the problem persist)

### Relevant log output

```shell
╭─ 14:31:38 |  1 Jul, Saturday |   in     Desktop  Havoc-dev 
╰─❯ make client-build
╭─ 14:31:38 |  1 Jul, Saturday |   in     Desktop  Havoc-dev 
╰─❯ ./havoc client
[*] building client
-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.11.so (found suitable version "3.11.2", minimum required is "3") 
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/anoam/Desktop/Havoc-dev/client/Build
fatal: not a git repository (or any of the parent directories): .git
error: option `branch' requires a value
make: *** [makefile:33: client-build] Error 129
              _______           _______  _______ 
    │\     /│(  ___  )│\     /│(  ___  )(  ____ \
    │ )   ( ││ (   ) ││ )   ( ││ (   ) ││ (    \/
    │ (___) ││ (___) ││ │   │ ││ │   │ ││ │      
    │  ___  ││  ___  │( (   ) )│ │   │ ││ │      
    │ (   ) ││ (   ) │ \ \_/ / │ │   │ ││ │      
    │ )   ( ││ )   ( │  \   /  │ (___) ││ (____/\
    │/     \││/     \│   \_/   (_______)(_______/

         pwn and elevate until it's done

Error: fork/exec client/Havoc: no such file or directory
[14:31:53] [ERRO] Failed to execute havoc
```

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by 7igr3ss** [comment]
Try to install these dependencies: `sudo apt install -y git build-essential apt-utils cmake libfontconfig1 libglu1-mesa-dev libgtest-dev libspdlog-dev libboost-all-dev libncurses5-dev libgdbm-dev libssl-dev libreadline-dev libffi-dev libsqlite3-dev libbz2-dev mesa-common-dev qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools libqt5websockets5 libqt5websockets5-dev qtdeclarative5-dev golang-go qtbase5-dev libqt5websockets5-dev python3-dev libboost-all-dev mingw-w64 nasm`, delete the previous build you compiled "Havoc", and re-run the `make` command. That should solve the issue you are facing.

**Comment by raf181** [comment]
thanks, it worked
