### ISSUE TITLE
[File a bug report for the Demon Implant]: process list will cause demo.exe to no response

### ISSUE THREAD

**Issue by bb33bb** [HavocFramework/Havoc#362]
### What happened?

A bug happened!

![Screenshot from 2023-07-26 16-23-21](https://github.com/HavocFramework/Havoc/assets/5463104/2dbfb05a-ba65-45cf-86d0-6abcc98a8dc3)

### Did You Do a Pull First?

Latest (You performed a pull first)

### Did You Try With the Dev Branch?

Yes (You tried using the dev branch but the problem persist)

### Relevant log output

```shell
no
```

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by S4ntiagoP** [comment]
fixed already, reopen if needed
