### ISSUE TITLE
mac os run question???

### ISSUE THREAD

**Issue by pullghjunkkk** [HavocFramework/Havoc#367]
### Contact Details

chikkachunckc@gmail.com

### What's the issue?

chikkachun@chikdeMBP ~ % cd Havoc/Client

make

./Havoc
-- The C compiler identification is AppleClang 14.0.3.14030022
-- The CXX compiler identification is AppleClang 14.0.3.14030022
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning (dev) at CMakeLists.txt:165 (find_package):
  Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
  are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found PythonLibs: /Library/Frameworks/Python.framework/Versions/3.10/lib/libpython3.10.dylib (found version "3.10.9") 
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
CMake Error at /usr/local/lib/cmake/Qt5Core/Qt5CoreConfig.cmake:14 (message):
  The imported target "Qt5::Core" references the file

     "/usr/local/.//mkspecs/macx-clang"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/usr/local/lib/cmake/Qt5Core/Qt5CoreConfigExtras.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /usr/local/lib/cmake/Qt5Core/Qt5CoreConfigExtras.cmake:56 (_qt5_Core_check_file_exists)
  /usr/local/lib/cmake/Qt5Core/Qt5CoreConfig.cmake:227 (include)
  /usr/local/lib/cmake/Qt5/Qt5Config.cmake:28 (find_package)
  CMakeLists.txt:167 (find_package)

-- Configuring incomplete, errors occurred!
make: *** [all] Error 1
dyld[85268]: Library not loaded: /Library/Frameworks/Python.framework/Versions/3.8/Python
  Referenced from: <A9E17D4E-0FE8-3278-BBB1-38D0331C7941> /Users/chikkachun/Havoc/Client/Havoc
  Reason: tried: '/Library/Frameworks/Python.framework/Versions/3.8/Python' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/Python.framework/Versions/3.8/Python' (no such file), '/Library/Frameworks/Python.framework/Versions/3.8/Python' (no such file), '/System/Library/Frameworks/Python.framework/Versions/3.8/Python' (no such file, not in dyld cache)
zsh: abort      ./Havoc

### Did You Do a Pull First?

Latest (You performed a pull first)

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for identification and remediation of the issue.

**Comment by S4ntiagoP** [comment]
havoc is not designed to run on Mac, although I understand that the client does run on it.

**Comment by Arks7** [comment]
Add to：
<img width="868" alt="image" src="https://github.com/HavocFramework/Havoc/assets/82130343/ef0b0e7d-b4e1-42c4-99d3-26cebdf6cae5">

Ran up：
<img width="952" alt="image" src="https://github.com/HavocFramework/Havoc/assets/82130343/16d036c0-c7ac-4b61-8004-f7e4427db89e">

Font size：
<img width="872" alt="image" src="https://github.com/HavocFramework/Havoc/assets/82130343/534e25a4-d5f6-4318-a75e-65a29ec515b0">
Ran up：
<img width="944" alt="image" src="https://github.com/HavocFramework/Havoc/assets/82130343/80fba5a7-046f-4c05-8a23-9551989a5121">
