### ISSUE TITLE
[enhancement] threaded BOFs without breaking sleep obf

### ISSUE THREAD

**Issue by CodeXTF2** [HavocFramework/Havoc#37]
maybe have the bof write output to a pipe and the agent can read it on wake. and dont encrypt the bof memory ofc.
Austin suggestion for the implementation:
```
write a position indendent bof loader, inject it with the BOF, go to sleep. IF the COFF needs to write output, design the BeaconPrintf() API to write to a pipe to read it from the agent.
```

**Comment by Cracked5pider** [comment]
meh wont do that in the public version. Might do it soon in a private release.....
