### ISSUE TITLE
[File a bug report for the Demon Implant]: Cannot execute payload on x86

### ISSUE THREAD

**Issue by gobiursus** [HavocFramework/Havoc#372]
### What happened?

Payload cannot be executed on X86 machine.

### Did You Do a Pull First?

Latest (You performed a pull first)

### Did You Try With the Dev Branch?

Yes (You tried using the dev branch but the problem persist)

### Relevant log output

```shell
stdapi_sys_process_execute: Operation failed: The version of %1 is not compatible with the version you're running. Check your computer's system information to see whether you need a x86 ; or x64 ; version of the program, and then contact the software publisher.
```

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by Cracked5pider** [comment]
did you generate an x86 payload ?

**Comment by S4ntiagoP** [comment]
make sure you are running a x86 binary, reopen if needed.

**Comment by gobiursus** [comment]
> did you generate an x86 payload ?

Yes.

**Comment by gobiursus** [comment]
> make sure you are running a x86 binary, reopen if needed.

Sorry I was busy last week. I was running a x86 binary. X64 compiler seems like the only thing available under `data/x86_64-w64-mingw32-cross/bin/`. Please help me to reopen it.
