### ISSUE TITLE
[Teamserver-Client--Bug]: Dotnet inline-execute & execute ERROR - Execution failed or CLR failed

### ISSUE THREAD

**Issue by vatsalgupta67** [HavocFramework/Havoc#374]
### What happened?

I was trying to execute mimikatz and  many other executables too but got an error again and again - **ERROR : Execution failed or CLR failed** something.

I also tried with privileged user and spent over hours to fix but nothing worked ! 

- Not only mimikatz, I actually tried executing other Recon executables & same output.

### Did You Do a Pull First?

Latest (You performed a pull first)

### Did You Try With the Dev Branch?

Yes (You tried using the dev branch but the problem persist)

### Relevant log output

```shell
dotnet inline-execute /usr/share/windows-resources/mimikatz/x64/mimikatz.exe coffee exit
[*] [F5ECB879] Tasked demon to inline execute a dotnet assembly: /usr/share/windows-resources/mimikatz/x64/mimikatz.exe
[+] Send Task to Agent [200 bytes]
[*] [HwBpEngine] Amsi/Etw has been hooked & patched
[*] Using CLR Version: v4.0.30319
[!] Failed to execute assembly or initialize the clr
```

### Did You Read Over Your Issue First?

- [x] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by S4ntiagoP** [comment]
that module is only for .NET binaries

**Comment by vatsalgupta67** [comment]
I tried Rubeus.exe and still not working !!!

**Comment by S4ntiagoP** [comment]
It works for me, can you share logs/screenshots?

**Comment by vatsalgupta67** [comment]
Hi, now it worked 😊. As you said that only.NET binaries are supported. But I used & saw non-dotnet executables running through "dotnet inline-execute". So, from now only dotnet is supported or non-dotnet too ?

Can we implement something for non-dotnet binaries too ? I was recently doing Red Team Engagements and found Havoc is awesome. But on other hand, it should be supported for non - dotnet binaries. Also can we implement interactive shell ( it'll be handy)

Thanks for your precious time!!!
