### ISSUE TITLE
Error with session remove

### ISSUE THREAD

**Issue by daniel2005d** [HavocFramework/Havoc#380]
### Contact Details

daniel2005d@gmail.com

### What happened?

I remove the dead session and reopen Havoc client and this session appear again. It must delete forever and not appear again.

### Did You Do a Pull First?

Latest (You performed a pull first)

### Did You Try With the Dev Branch?

Yes (You tried using the dev branch but the problem persist)

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by S4ntiagoP** [comment]
this should be fixed in dev, reopen if needed

**Comment by hastalamuerte** [comment]
same, cant reconnect one of sessions. can i clean cache of em? stable / kali
