### ISSUE TITLE
Installing the latest version

### ISSUE THREAD

**Issue by daniel2005d** [HavocFramework/Havoc#381]
### What's the issue?

I follow the wiki instructions for install the new version of Havoc, but with make ts-build command raise an error:

[*] building teamserver                                                                                                                                                                     
# Havoc/cmd/server                                                                                                                                                                          
cmd/server/teamserver.go:197:15: undefined: service                                                                                                                                         
make: *** [makefile:12: ts-build] Error 1

### Did You Do a Pull First?

Latest (You performed a pull first)

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for identification and remediation of the issue.

**Comment by roflsandwich** [comment]
I am experiencing the same problem. Fixed by downloading the previous version of teamserver.go

**Comment by 827Dream** [comment]
me too

**Comment by daniel2005d** [comment]
Fixed installing the dev branch

**Comment by Cracked5pider** [comment]
should be fixed now.
