### ISSUE TITLE
[Teamserver-Client--Bug]: socks clear lead to client and teamserver exit

### ISSUE THREAD

**Issue by ggg4566** [HavocFramework/Havoc#385]
### What happened?

when agent create socks tunnel  and clear socks cmd lead to client and teamserver exit
ex: 
socks add 4545 
socks add 4545
socks clear

teamserver console error:
panic: runtime error: index out of range [1] with length 1

goroutine 38 [running]:
Havoc/pkg/agent.(*Agent).TaskPrepare(0xc0000e42c0, 0x9ec, {0xca8d00?, 0xc0003ca810}, 0xc0000147d8, {0xc000267e10, 0x6}, {0xec4538, 0xc0003468c0})
        /home/kali/havoc/Havoc-main/teamserver/pkg/agent/demons.go:1949 +0xa7c5
Havoc/cmd/server.(*Teamserver).DispatchEvent(0xc0003468c0, {{0x7, {0xc00011a7f0, 0x3}, {0xc000120ba0, 0x13}, {0x0, 0x0}}, {0x3, 0xc0003ca810}})
        /home/kali/havoc/Havoc-main/teamserver/cmd/server/dispatch.go:190 +0x38eb
Havoc/cmd/server.(*Teamserver).handleRequest(0xc0003468c0, {0xc000267e10, 0x6})
        /home/kali/havoc/Havoc-main/teamserver/cmd/server/teamserver.go:623 +0x1015
created by Havoc/cmd/server.(*Teamserver).Start.func2
        /home/kali/havoc/Havoc-main/teamserver/cmd/server/teamserver.go:106 +0x24d
<img width="1020" alt="image" src="https://github.com/HavocFramework/Havoc/assets/7532477/53254df8-9ae0-41fd-a55b-e5dffec8f9fd">

**Comment by S4ntiagoP** [comment]
fixed on dev, thank you for reporting!
