### ISSUE TITLE
[Teamserver-Client--Bug]: jump-exec psexec code bug

### ISSUE THREAD

**Issue by zusda** [HavocFramework/Havoc#386]
I install Havoc as wiki said.
when I use the jump-exec module, error happen. And i check the py code. Found that the number 3 should be change to 4.
<img width="503" alt="bda990b9dcaee027f2f2ca823cf0f2c" src="https://github.com/HavocFramework/Havoc/assets/37831737/e4362cec-4cdc-4259-bce7-8d2de300ce9d">

<img width="350" alt="81649a24ed09778c18f44d18e9a6d81" src="https://github.com/HavocFramework/Havoc/assets/37831737/8ac29e05-7d18-42b2-a8ec-135db12711ed">

**Comment by daniel2005d** [comment]
These fix it's correct. That change work 4 me.

![image](https://github.com/HavocFramework/Havoc/assets/9272841/064040b3-3d4e-4cbf-8483-f8613b998493)

**Comment by S4ntiagoP** [comment]
thank you for reporting and the fix 😄 
this is now fixed on the dev branch
