### ISSUE TITLE
[Teamserver-Client--Bug]: sleep Obfuscation technique is undefined

### ISSUE THREAD

**Issue by netrebi** [HavocFramework/Havoc#391]
### Contact Details

igor.netrebko@proton.me

### What happened?

After fresh install of Havocon fres Ubuntu 22.4 and setup of http listener an agent build fails with error: 
"[-] sleep Obfuscation technique is undefined"

No agent is generated, can you please suggest? All values for payload deployment are default

### Did You Do a Pull First?

Latest (You performed a pull first)

### Did You Try With the Dev Branch?

No (You only tried the main branch...)

### Relevant log output

```shell
[*] starting build
[*] indirect syscalls has been enabled
[*] no sleep obfuscation has been specified
[-] sleep Obfuscation technique is undefined
```

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by charnim** [comment]
Check if the client is 0.5 and the server 0.6, I had the same issue. You need to have same version on both.

**Comment by netrebi** [comment]
that was it, thanks a lot!

**Comment by S4ntiagoP** [comment]
reopen if needed
