### ISSUE TITLE
[File a bug report for the Demon Implant]: close invalid token handle in CommandProcList which will cause an exception

### ISSUE THREAD

**Issue by sh1xo** [HavocFramework/Havoc#393]
### What happened?

When ProcessOpen fails, the closed token handle in the previous loop will be closed again, which will cause an exception.
(https://github.com/HavocFramework/Havoc/blob/c393115fa1714748f368aff97e55da4aa81f5c56/payloads/Demon/Source/Core/Command.c#L641C1-L648)

### Did You Do a Pull First?

Anything else (You didn't pull...)

### Did You Try With the Dev Branch?

No (You only tried the main branch...)

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by S4ntiagoP** [comment]
fixed, thank you!
