### ISSUE TITLE
[Teamserver-Client--Bug]: 

### ISSUE THREAD

**Issue by hastalamuerte** [HavocFramework/Havoc#397]
### What happened?

└─# make client-build
[*] building client
mkdir: cannot create directory ‘client/Build’: File exists
CMake Warning (dev) at CMakeLists.txt:30 (find_package):
  Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
  are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done (0.0s)
-- Generating done (0.0s)
-- Build files have been written to: /root/Desktop/Havoc-dev/client/Build
fatal: not a git repository (or any of the parent directories): .git
error: option `branch' requires a value
make: *** [makefile:33: client-build] Error 129

even if i delete manually build directory before make - same issue
with client cleanup same issue.. 
in dev and in main branch. 

### Did You Do a Pull First?

Latest (You performed a pull first)

### Did You Try With the Dev Branch?

Yes (You tried using the dev branch but the problem persist)

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by hastalamuerte** [comment]
build client from makefile from client dir - seems it work now
./havoc client  - run ok

**Comment by S4ntiagoP** [comment]
reopen if needed
