### ISSUE TITLE
[QUICK FIX]: Kali Font Problem

### ISSUE THREAD

**Issue by byinarie** [HavocFramework/Havoc#401]
This appears to be happening due to the default Qt5 settings in the Qt5 Configuration tool but can be easily resolved by just switching the font like below:
![image](https://github.com/HavocFramework/Havoc/assets/20119926/06c1b9e8-78a9-49c2-a573-154de9306476)

**Comment by Cracked5pider** [comment]
yeah i need to find a way to forcefully and automatically do it while installing or starting the client.

**Comment by byinarie** [comment]
https://github.com/HavocFramework/Havoc/pull/405

This PR hopefully fixes it, its kinda janky but I tested it in a bunch of different ways and couldn't get it to not work.

**Comment by S4ntiagoP** [comment]
reopen if needed
