### ISSUE TITLE
[Teamserver-Client--Bug]: Client does not update "Last Seen" and "Health" tab on arrival of demon

### ISSUE THREAD

**Issue by rafale0n** [HavocFramework/Havoc#411]
### What happened?

Pull latest dev 0.6 havoc framework, connect, generate a demon. When there is a callback, the "Last Seen" and "Health" won't update. You can however execute commands.

### Did You Do a Pull First?

Latest (You performed a pull first)

### Did You Try With the Dev Branch?

Yes (You tried using the dev branch but the problem persist)

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by S4ntiagoP** [comment]
have you tried the dev branch?

**Comment by rafale0n** [comment]
Hey @S4ntiagoP , thanks for looking into it. Yes, I just did the latest git pull from the dev branch on Client and Teamserver , rebuilt both and the problem still persists.

**Comment by rafale0n** [comment]
Just to add to that to help you pinpoint the problem, the bug seems to be introduced in the dev branch. The main one updates the last seen correctly, but the health tab is still broken:
![image](https://github.com/HavocFramework/Havoc/assets/77019753/0c4d2774-971c-40b2-9cfd-d660ddc81639)

**Comment by rafale0n** [comment]
Problem solved, this issue can now be closed: 
![image](https://github.com/HavocFramework/Havoc/assets/77019753/ebcce8ee-af7e-4c6f-b79f-9a331eee4238)

This happened due to time difference between Client and a Teamserver.

**Comment by S4ntiagoP** [comment]
good to know
