### ISSUE TITLE
Qt5 Library Issue

### ISSUE THREAD

**Issue by ThePuteh** [HavocFramework/Havoc#453]
Ubuntu 22.04.3 LTS
Havoc

Through the Documentation from havocframework.com, there is a little missing regarding Qt5 library.

Buidling the Server its not an issue, BUT 
to the client side build, there will be an issue for those who install Qt5-default in which the websocket did not came with the Qt5-default package.

So you must seperately install the Qt5 Websocket modules first, check the modules in Qt5 directories library (to check its existency) and re-run the client side build.

Where Qt5-default did not come with Qt5websocket modules.

Hope this help.

**Comment by Cracked5pider** [comment]
not missing. it is stated there because i was aware of this issue. 

![image](https://github.com/HavocFramework/Havoc/assets/51360176/ca6c12ed-3d2b-450a-8755-5b05c3dc9648)

**Comment by ThePuteh** [comment]
For Ubuntu, which last qt5 was no longer supported since 21.04, so i think the documentation for kali and debian only is not accurate and should be include together with Ubuntu also ..
by the way, its still debian family, for those who know.

Use ubuntu here but skipped the Kali and Debian Distro Dependencies for websocket could be the reason.

Tq sir ..


________________________________
