### ISSUE TITLE
[Teamserver-Client--Bug]: Error: fork/exec client/Havoc: no such file or directory

### ISSUE THREAD

**Issue by scar77face** [HavocFramework/Havoc#482]
### Contact Details

tprest@my.hpu.edu

### What happened?

A bug happened!
Using Kali Linux and in the  [/home/user/Tools/Havoc] directory, teamserver is running and when trying to start the Havoc client (./havoc client) receive the following error:

Error: fork/exec client/Havoc: no such file or directory
[19:42:19] [ERRO] Failed to execute havoc

### Did You Do a Pull First?

Latest (You performed a pull first)

### Did You Try With the Dev Branch?

Yes (You tried using the dev branch but the problem persist)

### Relevant log output

```shell
./havoc client
              _______           _______  _______
    │\     /│(  ___  )│\     /│(  ___  )(  ____ \
    │ )   ( ││ (   ) ││ )   ( ││ (   ) ││ (    \/
    │ (___) ││ (___) ││ │   │ ││ │   │ ││ │
    │  ___  ││  ___  │( (   ) )│ │   │ ││ │
    │ (   ) ││ (   ) │ \ \_/ / │ │   │ ││ │
    │ )   ( ││ )   ( │  \   /  │ (___) ││ (____/\
    │/     \││/     \│   \_/   (_______)(_______/

         pwn and elevate until it's done

Error: fork/exec client/Havoc: no such file or directory
[20:39:50] [ERRO] Failed to execute havoc
```

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by Cracked5pider** [comment]
you have not compiled the client.
