### ISSUE TITLE
Fail into local proxy recognition

### ISSUE THREAD

**Issue by JBalanza** [HavocFramework/Havoc#490]
### What happened?

I'm running the demon in an environment where a global proxy is set up via a configuration script (Proxy settings > Automatic Proxy setup > Use setup script).

I noticed that in this environment, the proxy awareness of the daemon is not working at all (the PR https://github.com/HavocFramework/Havoc/pull/348 seems not to successfully detect the settings here) and it performs the requests ignoring the proxy, which ends up into not being able to connect to the teamserver.

I'm running the latest main version.

### Did You Try With the Dev Branch?

No (You only tried the main branch...)

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by navaneeth-dev** [comment]
Should be fixed by https://github.com/HavocFramework/Havoc/commit/9b8a104ba1f8b775c0cf9dd54bbddf7f6539ab2d .

**Comment by Cracked5pider** [comment]
thanks for the issue. i have been made aware of this a while ago and provided with a fix (as @navaneeth-dev has mentioned it it has been fixed in the 9b8a104ba1f8b775c0cf9dd54bbddf7f6539ab2d commit). 
Do you mind switching the branch to the dev branch and see if this fixes anything? Cheers <3

**Comment by JBalanza** [comment]
Thanks @Cracked5pider and @navaneeth-dev for the reply. I tested the dev branch on that environment and worked flawlessly 😄 thanks for the help.

**Comment by realalexandergeorgiev** [comment]
Can confirm, dev branch fixed it
