### ISSUE TITLE
PowerShell Script Import ?

### ISSUE THREAD

**Issue by clspejd** [HavocFramework/Havoc#492]
### What is the idea?

How to import Powershell script in it ???
I see there's script manager for python but where's for powershell ?? 
How to use Invoke-Mimikatz.ps1, how to import that ?

### Is_it_already_in?

No (You checked and it doesn't.)

### Are-You-Trolling?

- [X] I declare I made an effort and provided the necessary information for an understanding of the feature by the Framework authors.

**Comment by Cracked5pider** [comment]
there is no `powershell-import` for now. i would recommend you to base64 encode the module and prepend it to the powershell command. like this `powershell -e <your imported powershell module>; Invoke-Mimikatz`

**Comment by clspejd** [comment]
you have provided an alternative not solutions
Better keep this Issue open until powershell-import isn't implemented

**Comment by Cracked5pider** [comment]
i have stopped working on the old code base so don't expect any solutions anymore. 
powershell import will be implemented in the new release but no longer in the current version which is 0.7 hence I closed this issue.
