### ISSUE TITLE
[File a bug report for the Demon Implant]: dotnet inline execute crash process

### ISSUE THREAD

**Issue by clspejd** [HavocFramework/Havoc#494]
### What happened?

When I try to execute dotnet module, command:- dotnet inline-execute /file/path/binary.exe
Then the demon crashes and the process is terminated. There is no security solution enabled on the machine so it's not being terminated by any security solution.

The binary is a C# binary, for extraction of Chrome Passwords.
It works fine when dropped on disk and then executed from there, but didn't worked when used with Havoc :(

### Did You Try With the Dev Branch?

Yes (You tried using the dev branch but the problem persists)

### Relevant log output

```shell
There is no output log, simple the process terminates and the Agent become Unresponsive, that's all
```

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by Cracked5pider** [comment]
does the C# binary execute `System.Environment.Exit`? this might cause the process to exit.

**Comment by Cracked5pider** [comment]
better is to share what exact (public) C# binary got used and executed so I can look more into that

**Comment by clspejd** [comment]
> does the C# binary execute `System.Environment.Exit`? this might cause the process to exit.

Yeah, I just looked into that. The binary execute "System.Environment.Exit" which caused the process to exit.
