### ISSUE TITLE
[Teamserver-Client--Bug]: 

### ISSUE THREAD

**Issue by dlburket1** [HavocFramework/Havoc#507]
![Screenshot_4](https://github.com/user-attachments/assets/3d48d622-7b36-4483-9237-78f6f86524dc)

**Comment by dlburket1** [comment]
![Screenshot_4](https://github.com/user-attachments/assets/850e3596-ddde-4dc6-9cdd-3218bbc88cba)

**Comment by Cracked5pider** [comment]
What is the issue ?

**Comment by dlburket1** [comment]
> В чем проблема?

![Uploading Screenshot_5.jpg…]()

**Comment by Cracked5pider** [comment]
did you provide the right credentials? that matches the profile you have specified? could you please provide more information on what is happening?
