### ISSUE TITLE
[Feature Suggestions/Enhancements]: make it undetectable...

### ISSUE THREAD

**Issue by JadooChoi312** [HavocFramework/Havoc#518]
### What is the idea?

i think the payload is can be easily get detected by antivirus..even tho it got obfuscated...mybe improve the payload code so it more undetectable?

### Is_it_already_in?

No (You checked and it doesn't.)

### Are-You-Trolling?

- [X] I declare I made an effort and provided the necessary information for an understanding of the feature by the Framework authors.

**Comment by Cracked5pider** [comment]
LMFAO

**Comment by trickster0** [comment]
Can we reopen this? You really need to make this FUD! @Cracked5pider
