### ISSUE TITLE
[Feature Suggestions/Enhancements]: Why it doesn't have Module to delete ?

### ISSUE THREAD

**Issue by clspejd** [HavocFramework/Havoc#525]
### What is the idea?

I was shocked to find that Havoc doesn't have any Module to delete File/Folders from the targets.

If I were to delete a file then I need to execute shell commend to achieve this. But seriously Havoc must have a Delete Module which overwrites the file before deleting and then delete the file.

If it can have cp to Copy a file, mv to Move a file, then why not del to Delete a file ?

### Is_it_already_in?

No (You checked and it doesn't.)

### Are-You-Trolling?

- [X] I declare I made an effort and provided the necessary information for an understanding of the feature by the Framework authors.

**Comment by Cracked5pider** [comment]
there is a `remove` command that allows you to delete files and directories
