### ISSUE TITLE
I can't install havoc on kali linux 

### ISSUE THREAD

**Issue by cino30** [HavocFramework/Havoc#536]
I wanted to install havoc on VMWARE's on vmimage's kalilinux.
However, I cannot install it.

git clone https://github.com/HavocFramework/Havoc.git
cd Havoc

sudo apt install -y git build-essential apt-utils cmake libfontconfig1 libglu1-mesa-dev libgtest-dev libspdlog-dev libboost-all-dev libncurses5-dev libgdbm-dev libssl-dev libreadline-dev libffi-dev libsqlite3-dev libbz2-dev mesa-common-dev qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools libqt5websockets5 libqt5websockets5-dev qtdeclarative5-dev golang-go qtbase5-dev libqt5websockets5-dev python3-dev libboost-all-dev mingw-w64 nasm

cd teamserver

go mod download golang.org/x/sys

go mod download github.com/ugorji/go

cd ..

make ts-build

I may not be able to download the go module, so I passed this and moved on.

>go mod download github.com/ugorji/go
go: module github.com/ugorji/go: not a known dependency

And if I try to build clint, it might stop at 11%.
make client-build

What should we do?
                        
![kali-linux-2024 3-vmware-amd64-2024-12-15-05-06-46](https://github.com/user-attachments/assets/1808497e-082a-4ea5-8f7d-00846b6aad9b)

**Comment by sycanz04** [comment]
Not sure about the others, but [this](https://github.com/HavocFramework/Havoc/issues/516#issuecomment-2489157015) helped solve the dependency issue. Try it out on your end too :)

**Comment by cino30** [comment]
I think this was my mistake.
havoc is running, now.

**Comment by liltoxicpain** [comment]
i'm still having the same issues. havoc client give me [ERRO] Failed to execute havoc , fork/exec client/Havoc: no such file or directory

**Comment by StormyAyo** [comment]
i seem to be stuck when trying to install Havoc during the make "ts-build command"..... Please anyone who can help with this? As a side note, i am using kali linux installed in a virtual box.

![Image](https://github.com/user-attachments/assets/e1521580-7e55-4eac-acb9-f3270cccdcb1)

![Image](https://github.com/user-attachments/assets/dc8bff4f-9436-48f4-a5e8-a7380a1e2bfd)
