### ISSUE TITLE
Teamserver-Client: Payload Generation: Listener drop-down box is not dynamically updated

### ISSUE THREAD

**Issue by rmusser01** [HavocFramework/Havoc#66]
**Issue:**
When generating a payload, it is required that a listener be configured and available for the payload.
If a user starts the payload generation process, and then proceeds to create a Listener while doing so, that newly created listener will not be shown as available in the Payload generation window's drop-down box selection for Listeners.

Image of Listener drop down being selected in Payload generation window, with no changes observed after a Listener has been created with the Payload generation window still open:
![listeners-refresh](https://user-images.githubusercontent.com/1444720/190834954-015dd3e0-2bd6-4150-a114-deb7476e8bb2.png)

**Solution:**
Enable dynamic update of the Listener selection box based on available listeners.

**Comment by skin-xp** [comment]
<img width="1654" alt="图片" src="https://user-images.githubusercontent.com/62318378/194761932-10bc0005-daa8-4a9b-aa85-6f2bb7fe5099.png">
<img width="1356" alt="图片" src="https://user-images.githubusercontent.com/62318378/194761960-768e5c1c-e780-4998-bc5f-58964318dcf3.png">

**Comment by skin-xp** [comment]
HostBind?

**Comment by skin-xp** [comment]
Youtube has a video

**Comment by skin-xp** [comment]
<img width="511" alt="图片" src="https://user-images.githubusercontent.com/62318378/194762167-4634f27b-99fe-44dd-8b77-1e4855a6a191.png">

**Comment by skin-xp** [comment]
Why can't hostbind write the IP address of the external network

**Comment by Cracked5pider** [comment]
HostBind is a field where you specify the address that the teamserver should use to bind the listener on. you can use external addresses only those that the system provieds. if you wanna specify where the agent should callback then specify it in the Hosts field. thanks.
