### ISSUE TITLE
HTTP/HTTPS URIs Config Option Box

### ISSUE THREAD

**Issue by dmcxblue** [HavocFramework/Havoc#87]
When building an HTTP/HTTPS listener the URIs Box does not allow to the user to fill it. 
As well as the Headers Box
![image](https://user-images.githubusercontent.com/41899653/193319410-54a23f39-f5e2-49c5-a7a1-fe62bde9277c.png)

**Comment by Cracked5pider** [comment]
You need to right click to add Headers / Uris.

**Comment by Cracked5pider** [comment]
I noticed that it's poor design so I am going to redesign it later this day.

**Comment by dmcxblue** [comment]
All good, should have started randomly clicking, might have got it, Lol. Worked

**Comment by vysecurity** [comment]
Where do you specify the domain name?

**Comment by Cracked5pider** [comment]
In the host field (bind) for now, it's only supporting one callback host. going to add the ability to add more in the next few days.

**Comment by vysecurity** [comment]
Oh I have to set a /etc/hosts record?

**Comment by rmusser01** [comment]
Fixed in commit cea3b1f7921a9b240bba40a2e4554776d8d29731
