### ISSUE TITLE
sleep -1 causes int overflow 

### ISSUE THREAD

**Issue by CausticKirbyZ** [HavocFramework/Havoc#89]
Tasking a demon to sleep for negative (-1) seconds causes the demon to integer overflow on the number of seconds resulting in several years of sleep being applied

![image](https://user-images.githubusercontent.com/10190365/193330812-f158ae58-06ef-4b1d-9a46-63b46e301e74.png)
 
![image](https://user-images.githubusercontent.com/10190365/193330877-70250a65-834c-4d51-9502-5c18fc5be67a.png)

**Comment by chbGSmCm** [comment]
This needs to be resolved in both the Teamserver as well as the `ParseInt32` function in the implant. Also check for any other atoi/atof-parsers so this doesnt happen.

**Comment by Cracked5pider** [comment]
fixed in [d98f8b6](https://github.com/HavocFramework/Havoc/commit/d98f8b692b9c0fe79b6d153b6f34167589082789)
