### ISSUE TITLE
Impossible to Tunnel via ngrok or Cloudflared service

### ISSUE THREAD

**Issue by fendi1989** [HavocFramework/Havoc#93]
After multiple tests I couldn't use Havoc listeners to create a tunnel from services liken Ngrok and Cloudflared and make the request bounce to my localhost.

Idealy , the operator could create a Internal listener like https://192.168.0.2:8888 and configure the payload to callback to ngrok url or Cloudflare tunnel URL.

the payload configuration must be decoupled from the listener. I can make my payload callback to any WAN based adress and listen internally on the chosen port used by ngrok or Cloudlared for example. Thanks In advance.

**Comment by chvancooten** [comment]
Agree, the hostname (for callbacks) and listen IP (for the teamserver) should be decoupled.
A workaround to add the desired hostname (e.g. `https://YOUR-ID.eu.ngrok.io`) in the configuration, and then temporarily add this hostname to your teamserver's `/etc/hosts` file pointing to the IP `0.0.0.0`, before booting the teamserver. This will get the teamserver to listen on all interfaces, and the implants to connect back to the right host.

**Comment by mgeeky** [comment]
One dime from my side is that Cloudflare is known to mess around with Request headers. Some headers will be changed (compression, caching) others will get added (Cloudflare specific). 

That means, Teamserver has to have some flexibility in accepting requests in, regardless of their minor deviations from configured contract (in `profile.yaotl`). I banged my head against Cobalt+CloudFlare wall from every side possible :<

**Comment by Cracked5pider** [comment]
I think I can close this issue since it has been resolved by adding multiple callback hosts to the listener. Thanks a lot for reporting and testing Havoc. You can reopen the issue if you still get this issue.
